# generated by datamodel-codegen:
#   filename:  https://github.com/microsoftgraph/msgraph-metadata/raw/refs/heads/master/openapi/v1.0/openapi.yaml
#   timestamp: 2025-01-31T10:52:52+00:00

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class ErrorDetails(BaseModel):
    code: str
    message: str
    target: str | None = None


class InnerError(BaseModel):
    request_id: Annotated[
        str | None, Field(description='Request Id as tracked internally by the service')
    ] = None
    client_request_id: Annotated[
        str | None,
        Field(description='Client request Id as sent by the client application.'),
    ] = None
    date: Annotated[
        datetime | None,
        Field(
            description='Date when the error occured.',

        ),
    ] = None
    field_odata_type: str


class MainError(BaseModel):
    code: str
    message: str
    target: str | None = None
    details: List[ErrorDetails] | None = None
    inner_error: InnerError | None = None


class ODataError(BaseModel):
    error: MainError
