# generated by datamodel-codegen:
#   filename:  https://github.com/microsoftgraph/msgraph-metadata/raw/refs/heads/master/openapi/v1.0/openapi.yaml
#   timestamp: 2025-01-31T10:52:52+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel, Field
from typing_extensions import Annotated

from ... import (
    BaseCollectionPaginationCountResponse,
)
from . import DevicePlatformType
from . import Entity


class AnswerKeyword(BaseModel):
    keywords: Annotated[
        List[str] | None,
        Field(
            description='A collection of keywords used to trigger the search answer.'
        ),
    ] = None
    match_similar_keywords: Annotated[
        bool | None,
        Field(
            description='If true, indicates that the search term contains similar words to the keywords that should trigger the search answer.'
        ),
    ] = None
    reserved_keywords: Annotated[
        List[str] | None,
        Field(
            description='Unique keywords that guarantee the search answer is triggered.'
        ),
    ] = None
    field_odata_type: str


class AnswerVariant(BaseModel):
    description: Annotated[
        str | None,
        Field(
            description='The answer variation description that is shown on the search results page.'
        ),
    ] = None
    display_name: Annotated[
        str | None,
        Field(
            description='The answer variation name that is displayed in search results.'
        ),
    ] = None
    language_tag: Annotated[
        str | None,
        Field(description='The country or region that can view this answer variation.'),
    ] = None
    platform: Annotated[
        DevicePlatformType | Dict[str, Any] | None,
        Field(
            description='The device or operating system that can view this answer variation. Possible values are: android, androidForWork, ios, macOS, windowsPhone81, windowsPhone81AndLater, windows10AndLater, androidWorkProfile, unknown, androidASOP, androidMobileApplicationManagement, iOSMobileApplicationManagement, unknownFutureValue.'
        ),
    ] = None
    web_url: Annotated[
        str | None,
        Field(
            description="The URL link for the answer variation. When users select this answer variation from the search results, they're directed to the specified URL."
        ),
    ] = None
    field_odata_type: str


class Identity(BaseModel):
    display_name: str | None = None
    id: str | None = None
    field_odata_type: str


class IdentitySet(BaseModel):
    application: Identity | Dict[str, Any] | None = None
    device: Identity | Dict[str, Any] | None = None
    user: Identity | Dict[str, Any] | None = None
    field_odata_type: str


class AnswerState(Enum):
    published = 'published'
    draft = 'draft'
    excluded = 'excluded'
    unknown_future_value = 'unknownFutureValue'


class SearchAnswer(Entity):
    description: Annotated[
        str | None,
        Field(
            description='The search answer description that is shown on the search results page.'
        ),
    ] = None
    display_name: Annotated[
        str | None,
        Field(
            description='The search answer name that is displayed in search results.'
        ),
    ] = None
    last_modified_by: Annotated[
        IdentitySet | Dict[str, Any] | None,
        Field(
            description='Details of the user who created or last modified the search answer. Read-only.'
        ),
    ] = None
    last_modified_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time when the search answer was created or last edited. The timestamp type represents date and time information using ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.',

        ),
    ] = None
    web_url: Annotated[
        str | None,
        Field(
            description='The URL link for the search answer. When users select this search answer from the search results, they are directed to the specified URL.'
        ),
    ] = None
    field_odata_type: str


class AnswerVariantCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[AnswerVariant] | None = None


class Acronym(SearchAnswer):
    stands_for: Annotated[
        str | None, Field(description='What the acronym stands for.')
    ] = None
    state: AnswerState | None = None
    field_odata_type: str


class Bookmark(SearchAnswer):
    availability_end_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time when the bookmark stops appearing as a search result. Set as null for always available. The timestamp type represents date and time information using ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.',

        ),
    ] = None
    availability_start_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time when the bookmark starts to appear as a search result. Set as null for always available. The timestamp type represents date and time information using ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.',

        ),
    ] = None
    categories: Annotated[
        List[str] | None,
        Field(
            description='Categories commonly used to describe this bookmark. For example, IT and HR.'
        ),
    ] = None
    group_ids: Annotated[
        List[str] | None,
        Field(
            description='The list of security groups that are able to view this bookmark.'
        ),
    ] = None
    is_suggested: Annotated[
        bool | None,
        Field(
            description='True if this bookmark was suggested to the admin, by a user, or was mined and suggested by Microsoft. Read-only.'
        ),
    ] = None
    keywords: Annotated[
        AnswerKeyword | Dict[str, Any] | None,
        Field(
            description='Keywords that trigger this bookmark to appear in search results.'
        ),
    ] = None
    language_tags: Annotated[
        List[str] | None,
        Field(
            description='A list of geographically specific language names in which this bookmark can be viewed. Each language tag value follows the pattern {language}-{region}. For example, en-us is English as used in the United States. For the list of possible values, see Supported language tags.'
        ),
    ] = None
    platforms: Annotated[
        List[DevicePlatformType] | None,
        Field(
            description='List of devices and operating systems that are able to view this bookmark. Possible values are: android, androidForWork, ios, macOS, windowsPhone81, windowsPhone81AndLater, windows10AndLater, androidWorkProfile, unknown, androidASOP, androidMobileApplicationManagement, iOSMobileApplicationManagement, unknownFutureValue.'
        ),
    ] = None
    power_app_ids: Annotated[
        List[str] | None,
        Field(
            description='List of Power Apps associated with this bookmark. If users add existing Power Apps to a bookmark, they can complete tasks directly on the search results page, such as entering vacation time or reporting expenses.'
        ),
    ] = None
    state: AnswerState | None = None
    targeted_variations: Annotated[
        List[AnswerVariant] | None,
        Field(
            description='Variations of a bookmark for different countries or devices. Use when you need to show different content to users based on their device, country/region, or both. The date and group settings apply to all variations.'
        ),
    ] = None
    field_odata_type: str


class Qna(SearchAnswer):
    availability_end_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time when the QnA stops appearing as a search result. Set as null for always available. The timestamp type represents date and time information using ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.',

        ),
    ] = None
    availability_start_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time when the QnA starts to appear as a search result. Set as null for always available. The timestamp type represents date and time information using ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.',

        ),
    ] = None
    group_ids: Annotated[
        List[str] | None,
        Field(
            description='The list of security groups that are able to view this QnA.'
        ),
    ] = None
    is_suggested: Annotated[
        bool | None,
        Field(
            description='True if a user or Microsoft suggested this QnA to the admin. Read-only.'
        ),
    ] = None
    keywords: Annotated[
        AnswerKeyword | Dict[str, Any] | None,
        Field(
            description='Keywords that trigger this QnA to appear in search results.'
        ),
    ] = None
    language_tags: Annotated[
        List[str] | None,
        Field(
            description='A list of geographically specific language names in which this QnA can be viewed. Each language tag value follows the pattern {language}-{region}. For example, en-us is English as used in the United States. For the list of possible values, see Supported language tags.'
        ),
    ] = None
    platforms: Annotated[
        List[DevicePlatformType] | None,
        Field(
            description='List of devices and operating systems that are able to view this QnA. Possible values are: android, androidForWork, ios, macOS, windowsPhone81, windowsPhone81AndLater, windows10AndLater, androidWorkProfile, unknown, androidASOP, androidMobileApplicationManagement, iOSMobileApplicationManagement, unknownFutureValue.'
        ),
    ] = None
    state: AnswerState | None = None
    targeted_variations: Annotated[
        List[AnswerVariant] | None,
        Field(
            description='Variations of a QnA for different countries or devices. Use when you need to show different content to users based on their device, country/region, or both. The date and group settings apply to all variations.'
        ),
    ] = None
    field_odata_type: str


class AcronymCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Acronym] | None = None


class BookmarkCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Bookmark] | None = None


class QnaCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Qna] | None = None
