# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-02-12T03:19:32+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel, Field

from . import KeyValue
from . import Entity


class LocalizedDescription(BaseModel):
    field_odata_type: str
    description: str | None = Field(
        None, description='The description in the localized language.'
    )
    language_tag: str | None = Field(
        None, description='The language tag for the label.'
    )


class LocalizedLabel(BaseModel):
    field_odata_type: str
    is_default: bool | None = Field(
        None, description='Indicates whether the label is the default label.'
    )
    language_tag: str | None = Field(
        None, description='The language tag for the label.'
    )
    name: str | None = Field(None, description='The name of the label.')


class LocalizedName(BaseModel):
    field_odata_type: str
    language_tag: str | None = Field(
        None, description='The language tag for the label.'
    )
    name: str | None = Field(None, description='The name in the localized language.')


class RelationType(Enum):
    pin = 'pin'
    reuse = 'reuse'
    unknown_future_value = 'unknownFutureValue'


class TermGroupScope(Enum):
    global_ = 'global'
    system = 'system'
    site_collection = 'siteCollection'
    unknown_future_value = 'unknownFutureValue'


class Group(Entity):
    field_odata_type: str
    created_date_time: datetime | None = Field(
        None, description='Date and time of the group creation. Read-only.'
    )
    description: str | None = Field(
        None, description='Description that gives details on the term usage.'
    )
    display_name: str | None = Field(None, description='Name of the group.')
    parent_site_id: str | None = Field(
        None, description='ID of the parent site of this group.'
    )
    scope: TermGroupScope | Dict[str, Any] | None = Field(
        None,
        description='Returns the type of the group. Possible values are: global, system, and siteCollection.',
    )
    sets: List[Set] | None = Field(
        None, description='All sets under the group in a term [store].'
    )


class Relation(Entity):
    field_odata_type: str
    from_term: Term | Dict[str, Any] | None = Field(
        None,
        description='The from [term] of the relation. The term from which the relationship is defined. A null value would indicate the relation is directly with the [set].',
    )
    relationship: RelationType | Dict[str, Any] | None = Field(
        None, description='The type of relation. Possible values are: pin, reuse.'
    )
    set: Set | Dict[str, Any] | None = Field(
        None, description='The [set] in which the relation is relevant.'
    )
    to_term: Term | Dict[str, Any] | None = Field(
        None,
        description='The to [term] of the relation. The term to which the relationship is defined.',
    )


class Set(Entity):
    field_odata_type: str
    children: List[Term] | None = Field(
        None, description='Children terms of set in term [store].'
    )
    created_date_time: datetime | None = Field(
        None, description='Date and time of set creation. Read-only.'
    )
    description: str | None = Field(
        None, description='Description that gives details on the term usage.'
    )
    localized_names: List[LocalizedName] | None = Field(
        None, description='Name of the set for each languageTag.'
    )
    parent_group: Group | None = None
    properties: List[KeyValue] | None = Field(
        None, description='Custom properties for the set.'
    )
    relations: List[Relation] | None = Field(
        None,
        description='Indicates which terms have been pinned or reused directly under the set.',
    )
    terms: List[Term] | None = Field(None, description='All the terms under the set.')


class Store(Entity):
    field_odata_type: str
    default_language_tag: str | None = Field(
        None, description='Default language of the term store.'
    )
    groups: List[Group] | None = Field(
        None, description='Collection of all groups available in the term store.'
    )
    language_tags: List[str] | None = Field(
        None, description='List of languages for the term store.'
    )
    sets: List[Set] | None = Field(
        None,
        description='Collection of all sets available in the term store. This relationship can only be used to load a specific term set.',
    )


class Term(Entity):
    field_odata_type: str
    children: List[Term] | None = Field(None, description='Children of current term.')
    created_date_time: datetime | None = Field(
        None, description='Date and time of term creation. Read-only.'
    )
    descriptions: List[LocalizedDescription] | None = Field(
        None, description='Description about term that is dependent on the languageTag.'
    )
    labels: List[LocalizedLabel] | None = Field(
        None, description='Label metadata for a term.'
    )
    last_modified_date_time: datetime | None = Field(
        None, description='Last date and time of term modification. Read-only.'
    )
    properties: List[KeyValue] | None = Field(
        None, description='Collection of properties on the term.'
    )
    relations: List[Relation] | None = Field(
        None,
        description='To indicate which terms are related to the current term as either pinned or reused.',
    )
    set: Set | Dict[str, Any] | None = Field(
        None, description='The [set] in which the term is created.'
    )

