# generated by datamodel-codegen:
#   filename:  https://github.com/microsoftgraph/msgraph-metadata/raw/refs/heads/master/openapi/v1.0/openapi.yaml
#   timestamp: 2025-01-31T10:52:52+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel, Field
from typing_extensions import Annotated

from ... import (
    BaseCollectionPaginationCountResponse,
)
from . import KeyValue
from . import Entity


class LocalizedDescription(BaseModel):
    description: Annotated[
        str | None, Field(description='The description in the localized language.')
    ] = None
    language_tag: Annotated[
        str | None, Field(description='The language tag for the label.')
    ] = None
    field_odata_type: str


class LocalizedLabel(BaseModel):
    is_default: Annotated[
        bool | None,
        Field(description='Indicates whether the label is the default label.'),
    ] = None
    language_tag: Annotated[
        str | None, Field(description='The language tag for the label.')
    ] = None
    name: Annotated[str | None, Field(description='The name of the label.')] = None
    field_odata_type: str


class LocalizedName(BaseModel):
    language_tag: Annotated[
        str | None, Field(description='The language tag for the label.')
    ] = None
    name: Annotated[
        str | None, Field(description='The name in the localized language.')
    ] = None
    field_odata_type: str


class RelationType(Enum):
    pin = 'pin'
    reuse = 'reuse'
    unknown_future_value = 'unknownFutureValue'


class TermGroupScope(Enum):
    global_ = 'global'
    system = 'system'
    site_collection = 'siteCollection'
    unknown_future_value = 'unknownFutureValue'


class LocalizedNameCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[LocalizedName] | None = None


class LocalizedDescriptionCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[LocalizedDescription] | None = None


class LocalizedLabelCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[LocalizedLabel] | None = None


class Group(Entity):
    created_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time of the group creation. Read-only.',
            pattern='^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$',
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(description='Description that gives details on the term usage.'),
    ] = None
    display_name: Annotated[str | None, Field(description='Name of the group.')] = None
    parent_site_id: Annotated[
        str | None, Field(description='ID of the parent site of this group.')
    ] = None
    scope: Annotated[
        TermGroupScope | Dict[str, Any] | None,
        Field(
            description='Returns the type of the group. Possible values are: global, system, and siteCollection.'
        ),
    ] = None
    sets: Annotated[
        List[Set] | None,
        Field(description='All sets under the group in a term [store].'),
    ] = None
    field_odata_type: str


class Relation(Entity):
    relationship: Annotated[
        RelationType | Dict[str, Any] | None,
        Field(description='The type of relation. Possible values are: pin, reuse.'),
    ] = None
    from_term: Annotated[
        Term | Dict[str, Any] | None,
        Field(
            description='The from [term] of the relation. The term from which the relationship is defined. A null value would indicate the relation is directly with the [set].'
        ),
    ] = None
    set: Annotated[
        Set | Dict[str, Any] | None,
        Field(description='The [set] in which the relation is relevant.'),
    ] = None
    to_term: Annotated[
        Term | Dict[str, Any] | None,
        Field(
            description='The to [term] of the relation. The term to which the relationship is defined.'
        ),
    ] = None
    field_odata_type: str


class Set(Entity):
    created_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time of set creation. Read-only.',
            pattern='^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$',
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(description='Description that gives details on the term usage.'),
    ] = None
    localized_names: Annotated[
        List[LocalizedName] | None,
        Field(description='Name of the set for each languageTag.'),
    ] = None
    properties: Annotated[
        List[KeyValue] | None, Field(description='Custom properties for the set.')
    ] = None
    children: Annotated[
        List[Term] | None, Field(description='Children terms of set in term [store].')
    ] = None
    parent_group: Group | None = None
    relations: Annotated[
        List[Relation] | None,
        Field(
            description='Indicates which terms have been pinned or reused directly under the set.'
        ),
    ] = None
    terms: Annotated[
        List[Term] | None, Field(description='All the terms under the set.')
    ] = None
    field_odata_type: str


class Store(Entity):
    default_language_tag: Annotated[
        str | None, Field(description='Default language of the term store.')
    ] = None
    language_tags: Annotated[
        List[str] | None, Field(description='List of languages for the term store.')
    ] = None
    groups: Annotated[
        List[Group] | None,
        Field(description='Collection of all groups available in the term store.'),
    ] = None
    sets: Annotated[
        List[Set] | None,
        Field(
            description='Collection of all sets available in the term store. This relationship can only be used to load a specific term set.'
        ),
    ] = None
    field_odata_type: str


class Term(Entity):
    created_date_time: Annotated[
        datetime | None,
        Field(
            description='Date and time of term creation. Read-only.',
            pattern='^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$',
        ),
    ] = None
    descriptions: Annotated[
        List[LocalizedDescription] | None,
        Field(
            description='Description about term that is dependent on the languageTag.'
        ),
    ] = None
    labels: Annotated[
        List[LocalizedLabel] | None, Field(description='Label metadata for a term.')
    ] = None
    last_modified_date_time: Annotated[
        datetime | None,
        Field(
            description='Last date and time of term modification. Read-only.',
            pattern='^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$',
        ),
    ] = None
    properties: Annotated[
        List[KeyValue] | None,
        Field(description='Collection of properties on the term.'),
    ] = None
    children: Annotated[
        List[Term] | None, Field(description='Children of current term.')
    ] = None
    relations: Annotated[
        List[Relation] | None,
        Field(
            description='To indicate which terms are related to the current term as either pinned or reused.'
        ),
    ] = None
    set: Annotated[
        Set | Dict[str, Any] | None,
        Field(description='The [set] in which the term is created.'),
    ] = None
    field_odata_type: str


class StoreCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Store] | None = None


class SetCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Set] | None = None


class TermCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Term] | None = None


class RelationCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Relation] | None = None


class GroupCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[Group] | None = None


Group.model_rebuild()
Relation.model_rebuild()
Set.model_rebuild()
