from __future__ import annotations
from typing import Optional
from typing import Union
from typing import Literal
from typing import Annotated
from datetime import datetime
from pydantic import BaseModel, Field, SerializeAsAny


class IosGeneralDeviceConfiguration(BaseModel):
	id: Optional[str] = Field(alias="id", default=None,)
	odata_type: Literal["#microsoft.graph.iosGeneralDeviceConfiguration"] = Field(alias="@odata.type", default="#microsoft.graph.iosGeneralDeviceConfiguration")
	createdDateTime: Optional[datetime] = Field(alias="createdDateTime", default=None,)
	description: Optional[str] = Field(alias="description", default=None,)
	deviceManagementApplicabilityRuleDeviceMode: Optional[DeviceManagementApplicabilityRuleDeviceMode] = Field(alias="deviceManagementApplicabilityRuleDeviceMode", default=None,)
	deviceManagementApplicabilityRuleOsEdition: Optional[DeviceManagementApplicabilityRuleOsEdition] = Field(alias="deviceManagementApplicabilityRuleOsEdition", default=None,)
	deviceManagementApplicabilityRuleOsVersion: Optional[DeviceManagementApplicabilityRuleOsVersion] = Field(alias="deviceManagementApplicabilityRuleOsVersion", default=None,)
	displayName: Optional[str] = Field(alias="displayName", default=None,)
	lastModifiedDateTime: Optional[datetime] = Field(alias="lastModifiedDateTime", default=None,)
	roleScopeTagIds: Optional[list[str]] = Field(alias="roleScopeTagIds", default=None,)
	supportsScopeTags: Optional[bool] = Field(alias="supportsScopeTags", default=None,)
	version: Optional[int] = Field(alias="version", default=None,)
	assignments: Optional[list[DeviceConfigurationAssignment]] = Field(alias="assignments", default=None,)
	deviceSettingStateSummaries: Optional[list[SettingStateDeviceSummary]] = Field(alias="deviceSettingStateSummaries", default=None,)
	deviceStatuses: Optional[list[DeviceConfigurationDeviceStatus]] = Field(alias="deviceStatuses", default=None,)
	deviceStatusOverview: Optional[DeviceConfigurationDeviceOverview] = Field(alias="deviceStatusOverview", default=None,)
	groupAssignments: Optional[list[DeviceConfigurationGroupAssignment]] = Field(alias="groupAssignments", default=None,)
	userStatuses: Optional[list[DeviceConfigurationUserStatus]] = Field(alias="userStatuses", default=None,)
	userStatusOverview: Optional[DeviceConfigurationUserOverview] = Field(alias="userStatusOverview", default=None,)
	accountBlockModification: Optional[bool] = Field(alias="accountBlockModification", default=None,)
	activationLockAllowWhenSupervised: Optional[bool] = Field(alias="activationLockAllowWhenSupervised", default=None,)
	airDropBlocked: Optional[bool] = Field(alias="airDropBlocked", default=None,)
	airDropForceUnmanagedDropTarget: Optional[bool] = Field(alias="airDropForceUnmanagedDropTarget", default=None,)
	airPlayForcePairingPasswordForOutgoingRequests: Optional[bool] = Field(alias="airPlayForcePairingPasswordForOutgoingRequests", default=None,)
	airPrintBlockCredentialsStorage: Optional[bool] = Field(alias="airPrintBlockCredentialsStorage", default=None,)
	airPrintBlocked: Optional[bool] = Field(alias="airPrintBlocked", default=None,)
	airPrintBlockiBeaconDiscovery: Optional[bool] = Field(alias="airPrintBlockiBeaconDiscovery", default=None,)
	airPrintForceTrustedTLS: Optional[bool] = Field(alias="airPrintForceTrustedTLS", default=None,)
	appClipsBlocked: Optional[bool] = Field(alias="appClipsBlocked", default=None,)
	appleNewsBlocked: Optional[bool] = Field(alias="appleNewsBlocked", default=None,)
	applePersonalizedAdsBlocked: Optional[bool] = Field(alias="applePersonalizedAdsBlocked", default=None,)
	appleWatchBlockPairing: Optional[bool] = Field(alias="appleWatchBlockPairing", default=None,)
	appleWatchForceWristDetection: Optional[bool] = Field(alias="appleWatchForceWristDetection", default=None,)
	appRemovalBlocked: Optional[bool] = Field(alias="appRemovalBlocked", default=None,)
	appsSingleAppModeList: Optional[list[Annotated[Union[AppleAppListItem]],Field(discriminator="odata_type")]]] = Field(alias="appsSingleAppModeList", default=None,)
	appStoreBlockAutomaticDownloads: Optional[bool] = Field(alias="appStoreBlockAutomaticDownloads", default=None,)
	appStoreBlocked: Optional[bool] = Field(alias="appStoreBlocked", default=None,)
	appStoreBlockInAppPurchases: Optional[bool] = Field(alias="appStoreBlockInAppPurchases", default=None,)
	appStoreBlockUIAppInstallation: Optional[bool] = Field(alias="appStoreBlockUIAppInstallation", default=None,)
	appStoreRequirePassword: Optional[bool] = Field(alias="appStoreRequirePassword", default=None,)
	appsVisibilityList: Optional[list[Annotated[Union[AppleAppListItem]],Field(discriminator="odata_type")]]] = Field(alias="appsVisibilityList", default=None,)
	appsVisibilityListType: Optional[AppListType | str] = Field(alias="appsVisibilityListType", default=None,)
	autoFillForceAuthentication: Optional[bool] = Field(alias="autoFillForceAuthentication", default=None,)
	autoUnlockBlocked: Optional[bool] = Field(alias="autoUnlockBlocked", default=None,)
	blockSystemAppRemoval: Optional[bool] = Field(alias="blockSystemAppRemoval", default=None,)
	bluetoothBlockModification: Optional[bool] = Field(alias="bluetoothBlockModification", default=None,)
	cameraBlocked: Optional[bool] = Field(alias="cameraBlocked", default=None,)
	cellularBlockDataRoaming: Optional[bool] = Field(alias="cellularBlockDataRoaming", default=None,)
	cellularBlockGlobalBackgroundFetchWhileRoaming: Optional[bool] = Field(alias="cellularBlockGlobalBackgroundFetchWhileRoaming", default=None,)
	cellularBlockPerAppDataModification: Optional[bool] = Field(alias="cellularBlockPerAppDataModification", default=None,)
	cellularBlockPersonalHotspot: Optional[bool] = Field(alias="cellularBlockPersonalHotspot", default=None,)
	cellularBlockPersonalHotspotModification: Optional[bool] = Field(alias="cellularBlockPersonalHotspotModification", default=None,)
	cellularBlockPlanModification: Optional[bool] = Field(alias="cellularBlockPlanModification", default=None,)
	cellularBlockVoiceRoaming: Optional[bool] = Field(alias="cellularBlockVoiceRoaming", default=None,)
	certificatesBlockUntrustedTlsCertificates: Optional[bool] = Field(alias="certificatesBlockUntrustedTlsCertificates", default=None,)
	classroomAppBlockRemoteScreenObservation: Optional[bool] = Field(alias="classroomAppBlockRemoteScreenObservation", default=None,)
	classroomAppForceUnpromptedScreenObservation: Optional[bool] = Field(alias="classroomAppForceUnpromptedScreenObservation", default=None,)
	classroomForceAutomaticallyJoinClasses: Optional[bool] = Field(alias="classroomForceAutomaticallyJoinClasses", default=None,)
	classroomForceRequestPermissionToLeaveClasses: Optional[bool] = Field(alias="classroomForceRequestPermissionToLeaveClasses", default=None,)
	classroomForceUnpromptedAppAndDeviceLock: Optional[bool] = Field(alias="classroomForceUnpromptedAppAndDeviceLock", default=None,)
	compliantAppListType: Optional[AppListType | str] = Field(alias="compliantAppListType", default=None,)
	compliantAppsList: Optional[list[Annotated[Union[AppleAppListItem]],Field(discriminator="odata_type")]]] = Field(alias="compliantAppsList", default=None,)
	configurationProfileBlockChanges: Optional[bool] = Field(alias="configurationProfileBlockChanges", default=None,)
	contactsAllowManagedToUnmanagedWrite: Optional[bool] = Field(alias="contactsAllowManagedToUnmanagedWrite", default=None,)
	contactsAllowUnmanagedToManagedRead: Optional[bool] = Field(alias="contactsAllowUnmanagedToManagedRead", default=None,)
	continuousPathKeyboardBlocked: Optional[bool] = Field(alias="continuousPathKeyboardBlocked", default=None,)
	dateAndTimeForceSetAutomatically: Optional[bool] = Field(alias="dateAndTimeForceSetAutomatically", default=None,)
	definitionLookupBlocked: Optional[bool] = Field(alias="definitionLookupBlocked", default=None,)
	deviceBlockEnableRestrictions: Optional[bool] = Field(alias="deviceBlockEnableRestrictions", default=None,)
	deviceBlockEraseContentAndSettings: Optional[bool] = Field(alias="deviceBlockEraseContentAndSettings", default=None,)
	deviceBlockNameModification: Optional[bool] = Field(alias="deviceBlockNameModification", default=None,)
	diagnosticDataBlockSubmission: Optional[bool] = Field(alias="diagnosticDataBlockSubmission", default=None,)
	diagnosticDataBlockSubmissionModification: Optional[bool] = Field(alias="diagnosticDataBlockSubmissionModification", default=None,)
	documentsBlockManagedDocumentsInUnmanagedApps: Optional[bool] = Field(alias="documentsBlockManagedDocumentsInUnmanagedApps", default=None,)
	documentsBlockUnmanagedDocumentsInManagedApps: Optional[bool] = Field(alias="documentsBlockUnmanagedDocumentsInManagedApps", default=None,)
	emailInDomainSuffixes: Optional[list[str]] = Field(alias="emailInDomainSuffixes", default=None,)
	enterpriseAppBlockTrust: Optional[bool] = Field(alias="enterpriseAppBlockTrust", default=None,)
	enterpriseAppBlockTrustModification: Optional[bool] = Field(alias="enterpriseAppBlockTrustModification", default=None,)
	enterpriseBookBlockBackup: Optional[bool] = Field(alias="enterpriseBookBlockBackup", default=None,)
	enterpriseBookBlockMetadataSync: Optional[bool] = Field(alias="enterpriseBookBlockMetadataSync", default=None,)
	esimBlockModification: Optional[bool] = Field(alias="esimBlockModification", default=None,)
	faceTimeBlocked: Optional[bool] = Field(alias="faceTimeBlocked", default=None,)
	filesNetworkDriveAccessBlocked: Optional[bool] = Field(alias="filesNetworkDriveAccessBlocked", default=None,)
	filesUsbDriveAccessBlocked: Optional[bool] = Field(alias="filesUsbDriveAccessBlocked", default=None,)
	findMyDeviceInFindMyAppBlocked: Optional[bool] = Field(alias="findMyDeviceInFindMyAppBlocked", default=None,)
	findMyFriendsBlocked: Optional[bool] = Field(alias="findMyFriendsBlocked", default=None,)
	findMyFriendsInFindMyAppBlocked: Optional[bool] = Field(alias="findMyFriendsInFindMyAppBlocked", default=None,)
	gameCenterBlocked: Optional[bool] = Field(alias="gameCenterBlocked", default=None,)
	gamingBlockGameCenterFriends: Optional[bool] = Field(alias="gamingBlockGameCenterFriends", default=None,)
	gamingBlockMultiplayer: Optional[bool] = Field(alias="gamingBlockMultiplayer", default=None,)
	hostPairingBlocked: Optional[bool] = Field(alias="hostPairingBlocked", default=None,)
	iBooksStoreBlocked: Optional[bool] = Field(alias="iBooksStoreBlocked", default=None,)
	iBooksStoreBlockErotica: Optional[bool] = Field(alias="iBooksStoreBlockErotica", default=None,)
	iCloudBlockActivityContinuation: Optional[bool] = Field(alias="iCloudBlockActivityContinuation", default=None,)
	iCloudBlockBackup: Optional[bool] = Field(alias="iCloudBlockBackup", default=None,)
	iCloudBlockDocumentSync: Optional[bool] = Field(alias="iCloudBlockDocumentSync", default=None,)
	iCloudBlockManagedAppsSync: Optional[bool] = Field(alias="iCloudBlockManagedAppsSync", default=None,)
	iCloudBlockPhotoLibrary: Optional[bool] = Field(alias="iCloudBlockPhotoLibrary", default=None,)
	iCloudBlockPhotoStreamSync: Optional[bool] = Field(alias="iCloudBlockPhotoStreamSync", default=None,)
	iCloudBlockSharedPhotoStream: Optional[bool] = Field(alias="iCloudBlockSharedPhotoStream", default=None,)
	iCloudPrivateRelayBlocked: Optional[bool] = Field(alias="iCloudPrivateRelayBlocked", default=None,)
	iCloudRequireEncryptedBackup: Optional[bool] = Field(alias="iCloudRequireEncryptedBackup", default=None,)
	iTunesBlocked: Optional[bool] = Field(alias="iTunesBlocked", default=None,)
	iTunesBlockExplicitContent: Optional[bool] = Field(alias="iTunesBlockExplicitContent", default=None,)
	iTunesBlockMusicService: Optional[bool] = Field(alias="iTunesBlockMusicService", default=None,)
	iTunesBlockRadio: Optional[bool] = Field(alias="iTunesBlockRadio", default=None,)
	keyboardBlockAutoCorrect: Optional[bool] = Field(alias="keyboardBlockAutoCorrect", default=None,)
	keyboardBlockDictation: Optional[bool] = Field(alias="keyboardBlockDictation", default=None,)
	keyboardBlockPredictive: Optional[bool] = Field(alias="keyboardBlockPredictive", default=None,)
	keyboardBlockShortcuts: Optional[bool] = Field(alias="keyboardBlockShortcuts", default=None,)
	keyboardBlockSpellCheck: Optional[bool] = Field(alias="keyboardBlockSpellCheck", default=None,)
	keychainBlockCloudSync: Optional[bool] = Field(alias="keychainBlockCloudSync", default=None,)
	kioskModeAllowAssistiveSpeak: Optional[bool] = Field(alias="kioskModeAllowAssistiveSpeak", default=None,)
	kioskModeAllowAssistiveTouchSettings: Optional[bool] = Field(alias="kioskModeAllowAssistiveTouchSettings", default=None,)
	kioskModeAllowAutoLock: Optional[bool] = Field(alias="kioskModeAllowAutoLock", default=None,)
	kioskModeAllowColorInversionSettings: Optional[bool] = Field(alias="kioskModeAllowColorInversionSettings", default=None,)
	kioskModeAllowRingerSwitch: Optional[bool] = Field(alias="kioskModeAllowRingerSwitch", default=None,)
	kioskModeAllowScreenRotation: Optional[bool] = Field(alias="kioskModeAllowScreenRotation", default=None,)
	kioskModeAllowSleepButton: Optional[bool] = Field(alias="kioskModeAllowSleepButton", default=None,)
	kioskModeAllowTouchscreen: Optional[bool] = Field(alias="kioskModeAllowTouchscreen", default=None,)
	kioskModeAllowVoiceControlModification: Optional[bool] = Field(alias="kioskModeAllowVoiceControlModification", default=None,)
	kioskModeAllowVoiceOverSettings: Optional[bool] = Field(alias="kioskModeAllowVoiceOverSettings", default=None,)
	kioskModeAllowVolumeButtons: Optional[bool] = Field(alias="kioskModeAllowVolumeButtons", default=None,)
	kioskModeAllowZoomSettings: Optional[bool] = Field(alias="kioskModeAllowZoomSettings", default=None,)
	kioskModeAppStoreUrl: Optional[str] = Field(alias="kioskModeAppStoreUrl", default=None,)
	kioskModeAppType: Optional[IosKioskModeAppType | str] = Field(alias="kioskModeAppType", default=None,)
	kioskModeBlockAutoLock: Optional[bool] = Field(alias="kioskModeBlockAutoLock", default=None,)
	kioskModeBlockRingerSwitch: Optional[bool] = Field(alias="kioskModeBlockRingerSwitch", default=None,)
	kioskModeBlockScreenRotation: Optional[bool] = Field(alias="kioskModeBlockScreenRotation", default=None,)
	kioskModeBlockSleepButton: Optional[bool] = Field(alias="kioskModeBlockSleepButton", default=None,)
	kioskModeBlockTouchscreen: Optional[bool] = Field(alias="kioskModeBlockTouchscreen", default=None,)
	kioskModeBlockVolumeButtons: Optional[bool] = Field(alias="kioskModeBlockVolumeButtons", default=None,)
	kioskModeBuiltInAppId: Optional[str] = Field(alias="kioskModeBuiltInAppId", default=None,)
	kioskModeEnableVoiceControl: Optional[bool] = Field(alias="kioskModeEnableVoiceControl", default=None,)
	kioskModeManagedAppId: Optional[str] = Field(alias="kioskModeManagedAppId", default=None,)
	kioskModeRequireAssistiveTouch: Optional[bool] = Field(alias="kioskModeRequireAssistiveTouch", default=None,)
	kioskModeRequireColorInversion: Optional[bool] = Field(alias="kioskModeRequireColorInversion", default=None,)
	kioskModeRequireMonoAudio: Optional[bool] = Field(alias="kioskModeRequireMonoAudio", default=None,)
	kioskModeRequireVoiceOver: Optional[bool] = Field(alias="kioskModeRequireVoiceOver", default=None,)
	kioskModeRequireZoom: Optional[bool] = Field(alias="kioskModeRequireZoom", default=None,)
	lockScreenBlockControlCenter: Optional[bool] = Field(alias="lockScreenBlockControlCenter", default=None,)
	lockScreenBlockNotificationView: Optional[bool] = Field(alias="lockScreenBlockNotificationView", default=None,)
	lockScreenBlockPassbook: Optional[bool] = Field(alias="lockScreenBlockPassbook", default=None,)
	lockScreenBlockTodayView: Optional[bool] = Field(alias="lockScreenBlockTodayView", default=None,)
	managedPasteboardRequired: Optional[bool] = Field(alias="managedPasteboardRequired", default=None,)
	mediaContentRatingApps: Optional[RatingAppsType | str] = Field(alias="mediaContentRatingApps", default=None,)
	mediaContentRatingAustralia: Optional[MediaContentRatingAustralia] = Field(alias="mediaContentRatingAustralia", default=None,)
	mediaContentRatingCanada: Optional[MediaContentRatingCanada] = Field(alias="mediaContentRatingCanada", default=None,)
	mediaContentRatingFrance: Optional[MediaContentRatingFrance] = Field(alias="mediaContentRatingFrance", default=None,)
	mediaContentRatingGermany: Optional[MediaContentRatingGermany] = Field(alias="mediaContentRatingGermany", default=None,)
	mediaContentRatingIreland: Optional[MediaContentRatingIreland] = Field(alias="mediaContentRatingIreland", default=None,)
	mediaContentRatingJapan: Optional[MediaContentRatingJapan] = Field(alias="mediaContentRatingJapan", default=None,)
	mediaContentRatingNewZealand: Optional[MediaContentRatingNewZealand] = Field(alias="mediaContentRatingNewZealand", default=None,)
	mediaContentRatingUnitedKingdom: Optional[MediaContentRatingUnitedKingdom] = Field(alias="mediaContentRatingUnitedKingdom", default=None,)
	mediaContentRatingUnitedStates: Optional[MediaContentRatingUnitedStates] = Field(alias="mediaContentRatingUnitedStates", default=None,)
	messagesBlocked: Optional[bool] = Field(alias="messagesBlocked", default=None,)
	networkUsageRules: Optional[list[IosNetworkUsageRule]] = Field(alias="networkUsageRules", default=None,)
	nfcBlocked: Optional[bool] = Field(alias="nfcBlocked", default=None,)
	notificationsBlockSettingsModification: Optional[bool] = Field(alias="notificationsBlockSettingsModification", default=None,)
	onDeviceOnlyDictationForced: Optional[bool] = Field(alias="onDeviceOnlyDictationForced", default=None,)
	onDeviceOnlyTranslationForced: Optional[bool] = Field(alias="onDeviceOnlyTranslationForced", default=None,)
	passcodeBlockFingerprintModification: Optional[bool] = Field(alias="passcodeBlockFingerprintModification", default=None,)
	passcodeBlockFingerprintUnlock: Optional[bool] = Field(alias="passcodeBlockFingerprintUnlock", default=None,)
	passcodeBlockModification: Optional[bool] = Field(alias="passcodeBlockModification", default=None,)
	passcodeBlockSimple: Optional[bool] = Field(alias="passcodeBlockSimple", default=None,)
	passcodeExpirationDays: Optional[int] = Field(alias="passcodeExpirationDays", default=None,)
	passcodeMinimumCharacterSetCount: Optional[int] = Field(alias="passcodeMinimumCharacterSetCount", default=None,)
	passcodeMinimumLength: Optional[int] = Field(alias="passcodeMinimumLength", default=None,)
	passcodeMinutesOfInactivityBeforeLock: Optional[int] = Field(alias="passcodeMinutesOfInactivityBeforeLock", default=None,)
	passcodeMinutesOfInactivityBeforeScreenTimeout: Optional[int] = Field(alias="passcodeMinutesOfInactivityBeforeScreenTimeout", default=None,)
	passcodePreviousPasscodeBlockCount: Optional[int] = Field(alias="passcodePreviousPasscodeBlockCount", default=None,)
	passcodeRequired: Optional[bool] = Field(alias="passcodeRequired", default=None,)
	passcodeRequiredType: Optional[RequiredPasswordType | str] = Field(alias="passcodeRequiredType", default=None,)
	passcodeSignInFailureCountBeforeWipe: Optional[int] = Field(alias="passcodeSignInFailureCountBeforeWipe", default=None,)
	passwordBlockAirDropSharing: Optional[bool] = Field(alias="passwordBlockAirDropSharing", default=None,)
	passwordBlockAutoFill: Optional[bool] = Field(alias="passwordBlockAutoFill", default=None,)
	passwordBlockProximityRequests: Optional[bool] = Field(alias="passwordBlockProximityRequests", default=None,)
	pkiBlockOTAUpdates: Optional[bool] = Field(alias="pkiBlockOTAUpdates", default=None,)
	podcastsBlocked: Optional[bool] = Field(alias="podcastsBlocked", default=None,)
	privacyForceLimitAdTracking: Optional[bool] = Field(alias="privacyForceLimitAdTracking", default=None,)
	proximityBlockSetupToNewDevice: Optional[bool] = Field(alias="proximityBlockSetupToNewDevice", default=None,)
	safariBlockAutofill: Optional[bool] = Field(alias="safariBlockAutofill", default=None,)
	safariBlocked: Optional[bool] = Field(alias="safariBlocked", default=None,)
	safariBlockJavaScript: Optional[bool] = Field(alias="safariBlockJavaScript", default=None,)
	safariBlockPopups: Optional[bool] = Field(alias="safariBlockPopups", default=None,)
	safariCookieSettings: Optional[WebBrowserCookieSettings | str] = Field(alias="safariCookieSettings", default=None,)
	safariManagedDomains: Optional[list[str]] = Field(alias="safariManagedDomains", default=None,)
	safariPasswordAutoFillDomains: Optional[list[str]] = Field(alias="safariPasswordAutoFillDomains", default=None,)
	safariRequireFraudWarning: Optional[bool] = Field(alias="safariRequireFraudWarning", default=None,)
	screenCaptureBlocked: Optional[bool] = Field(alias="screenCaptureBlocked", default=None,)
	sharedDeviceBlockTemporarySessions: Optional[bool] = Field(alias="sharedDeviceBlockTemporarySessions", default=None,)
	siriBlocked: Optional[bool] = Field(alias="siriBlocked", default=None,)
	siriBlockedWhenLocked: Optional[bool] = Field(alias="siriBlockedWhenLocked", default=None,)
	siriBlockUserGeneratedContent: Optional[bool] = Field(alias="siriBlockUserGeneratedContent", default=None,)
	siriRequireProfanityFilter: Optional[bool] = Field(alias="siriRequireProfanityFilter", default=None,)
	softwareUpdatesEnforcedDelayInDays: Optional[int] = Field(alias="softwareUpdatesEnforcedDelayInDays", default=None,)
	softwareUpdatesForceDelayed: Optional[bool] = Field(alias="softwareUpdatesForceDelayed", default=None,)
	spotlightBlockInternetResults: Optional[bool] = Field(alias="spotlightBlockInternetResults", default=None,)
	unpairedExternalBootToRecoveryAllowed: Optional[bool] = Field(alias="unpairedExternalBootToRecoveryAllowed", default=None,)
	usbRestrictedModeBlocked: Optional[bool] = Field(alias="usbRestrictedModeBlocked", default=None,)
	voiceDialingBlocked: Optional[bool] = Field(alias="voiceDialingBlocked", default=None,)
	vpnBlockCreation: Optional[bool] = Field(alias="vpnBlockCreation", default=None,)
	wallpaperBlockModification: Optional[bool] = Field(alias="wallpaperBlockModification", default=None,)
	wiFiConnectOnlyToConfiguredNetworks: Optional[bool] = Field(alias="wiFiConnectOnlyToConfiguredNetworks", default=None,)
	wiFiConnectToAllowedNetworksOnlyForced: Optional[bool] = Field(alias="wiFiConnectToAllowedNetworksOnlyForced", default=None,)
	wifiPowerOnForced: Optional[bool] = Field(alias="wifiPowerOnForced", default=None,)

from .device_management_applicability_rule_device_mode import DeviceManagementApplicabilityRuleDeviceMode
from .device_management_applicability_rule_os_edition import DeviceManagementApplicabilityRuleOsEdition
from .device_management_applicability_rule_os_version import DeviceManagementApplicabilityRuleOsVersion
from .device_configuration_assignment import DeviceConfigurationAssignment
from .setting_state_device_summary import SettingStateDeviceSummary
from .device_configuration_device_status import DeviceConfigurationDeviceStatus
from .device_configuration_device_overview import DeviceConfigurationDeviceOverview
from .device_configuration_group_assignment import DeviceConfigurationGroupAssignment
from .device_configuration_user_status import DeviceConfigurationUserStatus
from .device_configuration_user_overview import DeviceConfigurationUserOverview
from .apple_app_list_item import AppleAppListItem
from .apple_app_list_item import AppleAppListItem
from .app_list_type import AppListType
from .app_list_type import AppListType
from .apple_app_list_item import AppleAppListItem
from .ios_kiosk_mode_app_type import IosKioskModeAppType
from .rating_apps_type import RatingAppsType
from .media_content_rating_australia import MediaContentRatingAustralia
from .media_content_rating_canada import MediaContentRatingCanada
from .media_content_rating_france import MediaContentRatingFrance
from .media_content_rating_germany import MediaContentRatingGermany
from .media_content_rating_ireland import MediaContentRatingIreland
from .media_content_rating_japan import MediaContentRatingJapan
from .media_content_rating_new_zealand import MediaContentRatingNewZealand
from .media_content_rating_united_kingdom import MediaContentRatingUnitedKingdom
from .media_content_rating_united_states import MediaContentRatingUnitedStates
from .ios_network_usage_rule import IosNetworkUsageRule
from .required_password_type import RequiredPasswordType
from .web_browser_cookie_settings import WebBrowserCookieSettings

