from __future__ import annotations
from enum import StrEnum


class NetworkaccessRegion(StrEnum):
	eastUS = "eastUS"
	eastUS2 = "eastUS2"
	westUS = "westUS"
	westUS2 = "westUS2"
	westUS3 = "westUS3"
	centralUS = "centralUS"
	northCentralUS = "northCentralUS"
	southCentralUS = "southCentralUS"
	northEurope = "northEurope"
	westEurope = "westEurope"
	franceCentral = "franceCentral"
	germanyWestCentral = "germanyWestCentral"
	switzerlandNorth = "switzerlandNorth"
	ukSouth = "ukSouth"
	canadaEast = "canadaEast"
	canadaCentral = "canadaCentral"
	southAfricaWest = "southAfricaWest"
	southAfricaNorth = "southAfricaNorth"
	uaeNorth = "uaeNorth"
	australiaEast = "australiaEast"
	westCentralUS = "westCentralUS"
	centralIndia = "centralIndia"
	southEastAsia = "southEastAsia"
	swedenCentral = "swedenCentral"
	southIndia = "southIndia"
	australiaSouthEast = "australiaSouthEast"
	koreaCentral = "koreaCentral"
	polandCentral = "polandCentral"
	brazilSouth = "brazilSouth"
	japanEast = "japanEast"
	japanWest = "japanWest"
	koreaSouth = "koreaSouth"
	italyNorth = "italyNorth"
	franceSouth = "franceSouth"
	israelCentral = "israelCentral"
	unknownFutureValue = "unknownFutureValue"

