from __future__ import annotations
from enum import StrEnum


class PrinterProcessingStateReason(StrEnum):
	paused = "paused"
	mediaJam = "mediaJam"
	mediaNeeded = "mediaNeeded"
	mediaLow = "mediaLow"
	mediaEmpty = "mediaEmpty"
	coverOpen = "coverOpen"
	interlockOpen = "interlockOpen"
	outputTrayMissing = "outputTrayMissing"
	outputAreaFull = "outputAreaFull"
	markerSupplyLow = "markerSupplyLow"
	markerSupplyEmpty = "markerSupplyEmpty"
	inputTrayMissing = "inputTrayMissing"
	outputAreaAlmostFull = "outputAreaAlmostFull"
	markerWasteAlmostFull = "markerWasteAlmostFull"
	markerWasteFull = "markerWasteFull"
	fuserOverTemp = "fuserOverTemp"
	fuserUnderTemp = "fuserUnderTemp"
	other = "other"
	none = "none"
	movingToPaused = "movingToPaused"
	shutdown = "shutdown"
	connectingToDevice = "connectingToDevice"
	timedOut = "timedOut"
	stopping = "stopping"
	stoppedPartially = "stoppedPartially"
	tonerLow = "tonerLow"
	tonerEmpty = "tonerEmpty"
	spoolAreaFull = "spoolAreaFull"
	doorOpen = "doorOpen"
	opticalPhotoConductorNearEndOfLife = "opticalPhotoConductorNearEndOfLife"
	opticalPhotoConductorLifeOver = "opticalPhotoConductorLifeOver"
	developerLow = "developerLow"
	developerEmpty = "developerEmpty"
	interpreterResourceUnavailable = "interpreterResourceUnavailable"
	unknownFutureValue = "unknownFutureValue"

