from __future__ import annotations
from enum import StrEnum


class RecommendationType(StrEnum):
	adfsAppsMigration = "adfsAppsMigration"
	enableDesktopSSO = "enableDesktopSSO"
	enablePHS = "enablePHS"
	enableProvisioning = "enableProvisioning"
	switchFromPerUserMFA = "switchFromPerUserMFA"
	tenantMFA = "tenantMFA"
	thirdPartyApps = "thirdPartyApps"
	turnOffPerUserMFA = "turnOffPerUserMFA"
	useAuthenticatorApp = "useAuthenticatorApp"
	useMyApps = "useMyApps"
	staleApps = "staleApps"
	staleAppCreds = "staleAppCreds"
	applicationCredentialExpiry = "applicationCredentialExpiry"
	servicePrincipalKeyExpiry = "servicePrincipalKeyExpiry"
	adminMFAV2 = "adminMFAV2"
	blockLegacyAuthentication = "blockLegacyAuthentication"
	integratedApps = "integratedApps"
	mfaRegistrationV2 = "mfaRegistrationV2"
	pwagePolicyNew = "pwagePolicyNew"
	passwordHashSync = "passwordHashSync"
	oneAdmin = "oneAdmin"
	roleOverlap = "roleOverlap"
	selfServicePasswordReset = "selfServicePasswordReset"
	signinRiskPolicy = "signinRiskPolicy"
	userRiskPolicy = "userRiskPolicy"
	verifyAppPublisher = "verifyAppPublisher"
	privateLinkForAAD = "privateLinkForAAD"
	appRoleAssignmentsGroups = "appRoleAssignmentsGroups"
	appRoleAssignmentsUsers = "appRoleAssignmentsUsers"
	managedIdentity = "managedIdentity"
	overprivilegedApps = "overprivilegedApps"
	unknownFutureValue = "unknownFutureValue"
	longLivedCredentials = "longLivedCredentials"
	aadConnectDeprecated = "aadConnectDeprecated"
	adalToMsalMigration = "adalToMsalMigration"
	ownerlessApps = "ownerlessApps"
	inactiveGuests = "inactiveGuests"
	aadGraphDeprecationApplication = "aadGraphDeprecationApplication"
	aadGraphDeprecationServicePrincipal = "aadGraphDeprecationServicePrincipal"
	mfaServerDeprecation = "mfaServerDeprecation"

