from __future__ import annotations
from enum import StrEnum


class RemoteAction(StrEnum):
	unknown = "unknown"
	factoryReset = "factoryReset"
	removeCompanyData = "removeCompanyData"
	resetPasscode = "resetPasscode"
	remoteLock = "remoteLock"
	enableLostMode = "enableLostMode"
	disableLostMode = "disableLostMode"
	locateDevice = "locateDevice"
	rebootNow = "rebootNow"
	recoverPasscode = "recoverPasscode"
	cleanWindowsDevice = "cleanWindowsDevice"
	logoutSharedAppleDeviceActiveUser = "logoutSharedAppleDeviceActiveUser"
	quickScan = "quickScan"
	fullScan = "fullScan"
	windowsDefenderUpdateSignatures = "windowsDefenderUpdateSignatures"
	factoryResetKeepEnrollmentData = "factoryResetKeepEnrollmentData"
	updateDeviceAccount = "updateDeviceAccount"
	automaticRedeployment = "automaticRedeployment"
	shutDown = "shutDown"
	rotateBitLockerKeys = "rotateBitLockerKeys"
	rotateFileVaultKey = "rotateFileVaultKey"
	getFileVaultKey = "getFileVaultKey"
	setDeviceName = "setDeviceName"
	activateDeviceEsim = "activateDeviceEsim"
	deprovision = "deprovision"
	disable = "disable"
	reenable = "reenable"
	moveDeviceToOrganizationalUnit = "moveDeviceToOrganizationalUnit"
	initiateMobileDeviceManagementKeyRecovery = "initiateMobileDeviceManagementKeyRecovery"
	initiateOnDemandProactiveRemediation = "initiateOnDemandProactiveRemediation"
	rotateLocalAdminPassword = "rotateLocalAdminPassword"
	unknownFutureValue = "unknownFutureValue"
	launchRemoteHelp = "launchRemoteHelp"
	revokeAppleVppLicenses = "revokeAppleVppLicenses"
	removeDeviceFirmwareConfigurationInterfaceManagement = "removeDeviceFirmwareConfigurationInterfaceManagement"
	pauseConfigurationRefresh = "pauseConfigurationRefresh"
	initiateDeviceAttestation = "initiateDeviceAttestation"
	changeAssignments = "changeAssignments"
	delete = "delete"

