from __future__ import annotations
from enum import StrEnum


class ResponseEmotionType(StrEnum):
	none = "none"
	confident = "confident"
	excited = "excited"
	happy = "happy"
	motivated = "motivated"
	peaceful = "peaceful"
	ambitious = "ambitious"
	cheerful = "cheerful"
	comfortable = "comfortable"
	creative = "creative"
	determined = "determined"
	energized = "energized"
	focused = "focused"
	fulfilled = "fulfilled"
	grateful = "grateful"
	included = "included"
	inspired = "inspired"
	optimistic = "optimistic"
	proud = "proud"
	successful = "successful"
	valuable = "valuable"
	annoyed = "annoyed"
	bored = "bored"
	calm = "calm"
	confused = "confused"
	glad = "glad"
	content = "content"
	pensive = "pensive"
	reserved = "reserved"
	restless = "restless"
	shocked = "shocked"
	tired = "tired"
	angry = "angry"
	depressed = "depressed"
	exhausted = "exhausted"
	lonely = "lonely"
	nervous = "nervous"
	anxious = "anxious"
	apathetic = "apathetic"
	concerned = "concerned"
	disappointed = "disappointed"
	frightened = "frightened"
	frustrated = "frustrated"
	hopeless = "hopeless"
	hurt = "hurt"
	jealous = "jealous"
	miserable = "miserable"
	overwhelmed = "overwhelmed"
	skeptical = "skeptical"
	stressed = "stressed"
	stuck = "stuck"
	worthless = "worthless"
	awed = "awed"
	ashamed = "ashamed"
	curious = "curious"
	sensitive = "sensitive"
	sad = "sad"
	unknownFutureValue = "unknownFutureValue"

