from __future__ import annotations
from enum import StrEnum


class ResultantAppStateDetail(StrEnum):
	processorArchitectureNotApplicable = "processorArchitectureNotApplicable"
	minimumDiskSpaceNotMet = "minimumDiskSpaceNotMet"
	minimumOsVersionNotMet = "minimumOsVersionNotMet"
	minimumPhysicalMemoryNotMet = "minimumPhysicalMemoryNotMet"
	minimumLogicalProcessorCountNotMet = "minimumLogicalProcessorCountNotMet"
	minimumCpuSpeedNotMet = "minimumCpuSpeedNotMet"
	platformNotApplicable = "platformNotApplicable"
	fileSystemRequirementNotMet = "fileSystemRequirementNotMet"
	registryRequirementNotMet = "registryRequirementNotMet"
	powerShellScriptRequirementNotMet = "powerShellScriptRequirementNotMet"
	supersedingAppsNotApplicable = "supersedingAppsNotApplicable"
	noAdditionalDetails = "noAdditionalDetails"
	dependencyFailedToInstall = "dependencyFailedToInstall"
	dependencyWithRequirementsNotMet = "dependencyWithRequirementsNotMet"
	dependencyPendingReboot = "dependencyPendingReboot"
	dependencyWithAutoInstallDisabled = "dependencyWithAutoInstallDisabled"
	supersededAppUninstallFailed = "supersededAppUninstallFailed"
	supersededAppUninstallPendingReboot = "supersededAppUninstallPendingReboot"
	removingSupersededApps = "removingSupersededApps"
	iosAppStoreUpdateFailedToInstall = "iosAppStoreUpdateFailedToInstall"
	vppAppHasUpdateAvailable = "vppAppHasUpdateAvailable"
	userRejectedUpdate = "userRejectedUpdate"
	uninstallPendingReboot = "uninstallPendingReboot"
	supersedingAppsDetected = "supersedingAppsDetected"
	supersededAppsDetected = "supersededAppsDetected"
	seeInstallErrorCode = "seeInstallErrorCode"
	autoInstallDisabled = "autoInstallDisabled"
	managedAppNoLongerPresent = "managedAppNoLongerPresent"
	userRejectedInstall = "userRejectedInstall"
	userIsNotLoggedIntoAppStore = "userIsNotLoggedIntoAppStore"
	untargetedSupersedingAppsDetected = "untargetedSupersedingAppsDetected"
	appRemovedBySupersedence = "appRemovedBySupersedence"
	seeUninstallErrorCode = "seeUninstallErrorCode"
	pendingReboot = "pendingReboot"
	installingDependencies = "installingDependencies"
	contentDownloaded = "contentDownloaded"

