from __future__ import annotations
from enum import StrEnum


class SecurityAppCategory(StrEnum):
	security = "security"
	collaboration = "collaboration"
	hostingServices = "hostingServices"
	onlineMeetings = "onlineMeetings"
	newsAndEntertainment = "newsAndEntertainment"
	eCommerce = "eCommerce"
	education = "education"
	cloudStorage = "cloudStorage"
	marketing = "marketing"
	operationsManagement = "operationsManagement"
	health = "health"
	advertising = "advertising"
	productivity = "productivity"
	accountingAndFinance = "accountingAndFinance"
	contentManagement = "contentManagement"
	contentSharing = "contentSharing"
	businessManagement = "businessManagement"
	communications = "communications"
	dataAnalytics = "dataAnalytics"
	businessIntelligence = "businessIntelligence"
	webemail = "webemail"
	codeHosting = "codeHosting"
	webAnalytics = "webAnalytics"
	socialNetwork = "socialNetwork"
	crm = "crm"
	forums = "forums"
	humanResourceManagement = "humanResourceManagement"
	transportationAndTravel = "transportationAndTravel"
	productDesign = "productDesign"
	sales = "sales"
	cloudComputingPlatform = "cloudComputingPlatform"
	projectManagement = "projectManagement"
	personalInstantMessaging = "personalInstantMessaging"
	developmentTools = "developmentTools"
	itServices = "itServices"
	supplyChainAndLogistics = "supplyChainAndLogistics"
	propertyManagement = "propertyManagement"
	customerSupport = "customerSupport"
	internetOfThings = "internetOfThings"
	vendorManagementSystems = "vendorManagementSystems"
	websiteMonitoring = "websiteMonitoring"
	generativeAi = "generativeAi"
	unknown = "unknown"
	unknownFutureValue = "unknownFutureValue"

