from __future__ import annotations
from enum import StrEnum


class SecurityLogDataProvider(StrEnum):
	barracuda = "barracuda"
	bluecoat = "bluecoat"
	checkpoint = "checkpoint"
	ciscoAsa = "ciscoAsa"
	ciscoIronportProxy = "ciscoIronportProxy"
	fortigate = "fortigate"
	paloAlto = "paloAlto"
	squid = "squid"
	zscaler = "zscaler"
	mcafeeSwg = "mcafeeSwg"
	ciscoScanSafe = "ciscoScanSafe"
	juniperSrx = "juniperSrx"
	sophosSg = "sophosSg"
	websenseV75 = "websenseV75"
	websenseSiemCef = "websenseSiemCef"
	machineZoneMeraki = "machineZoneMeraki"
	squidNative = "squidNative"
	ciscoFwsm = "ciscoFwsm"
	microsoftIsaW3C = "microsoftIsaW3C"
	sonicwall = "sonicwall"
	sophosCyberoam = "sophosCyberoam"
	clavister = "clavister"
	customParser = "customParser"
	juniperSsg = "juniperSsg"
	zscalerQradar = "zscalerQradar"
	juniperSrxSd = "juniperSrxSd"
	juniperSrxWelf = "juniperSrxWelf"
	microsoftConditionalAppAccess = "microsoftConditionalAppAccess"
	ciscoAsaFirepower = "ciscoAsaFirepower"
	genericCef = "genericCef"
	genericLeef = "genericLeef"
	genericW3C = "genericW3C"
	iFilter = "iFilter"
	checkpointXml = "checkpointXml"
	checkpointSmartViewTracker = "checkpointSmartViewTracker"
	barracudaNextGenFw = "barracudaNextGenFw"
	barracudaNextGenFwWeblog = "barracudaNextGenFwWeblog"
	microsoftDefenderForEndpoint = "microsoftDefenderForEndpoint"
	zscalerCef = "zscalerCef"
	sophosXg = "sophosXg"
	iboss = "iboss"
	forcepoint = "forcepoint"
	fortios = "fortios"
	ciscoIronportWsaIi = "ciscoIronportWsaIi"
	paloAltoLeef = "paloAltoLeef"
	forcepointLeef = "forcepointLeef"
	stormshield = "stormshield"
	contentkeeper = "contentkeeper"
	ciscoIronportWsaIii = "ciscoIronportWsaIii"
	checkpointCef = "checkpointCef"
	corrata = "corrata"
	ciscoFirepowerV6 = "ciscoFirepowerV6"
	menloSecurityCef = "menloSecurityCef"
	watchguardXtm = "watchguardXtm"
	openSystemsSecureWebGateway = "openSystemsSecureWebGateway"
	wandera = "wandera"
	unknownFutureValue = "unknownFutureValue"

