from __future__ import annotations
from typing import Optional
from typing import Union
from typing import Annotated
from pydantic import BaseModel, Field


class UnifiedRoleManagementAlertConfigurationCollectionResponse(BaseModel):
	odata_count: Optional[int] = Field(alias="@odata.count", default=None,)
	odata_nextLink: Optional[str] = Field(alias="@odata.nextLink", default=None,)
	value: Optional[list[Annotated[Union[InvalidLicenseAlertConfiguration, NoMfaOnRoleActivationAlertConfiguration, RedundantAssignmentAlertConfiguration, RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration, SequentialActivationRenewalsAlertConfiguration, StaleSignInAlertConfiguration, TooManyGlobalAdminsAssignedToTenantAlertConfiguration],Field(discriminator="odata_type")]]] = Field(alias="value", default=None,)

from .invalid_license_alert_configuration import InvalidLicenseAlertConfiguration
from .no_mfa_on_role_activation_alert_configuration import NoMfaOnRoleActivationAlertConfiguration
from .redundant_assignment_alert_configuration import RedundantAssignmentAlertConfiguration
from .roles_assigned_outside_privileged_identity_management_alert_configuration import RolesAssignedOutsidePrivilegedIdentityManagementAlertConfiguration
from .sequential_activation_renewals_alert_configuration import SequentialActivationRenewalsAlertConfiguration
from .stale_sign_in_alert_configuration import StaleSignInAlertConfiguration
from .too_many_global_admins_assigned_to_tenant_alert_configuration import TooManyGlobalAdminsAssignedToTenantAlertConfiguration
