# generated by datamodel-codegen:
#   filename:  https://github.com/microsoftgraph/msgraph-metadata/raw/refs/heads/master/openapi/v1.0/openapi.yaml
#   timestamp: 2025-01-31T10:52:52+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, RootModel


class ODataCountResponse(RootModel[int]):
    root: int


class ReferenceUpdate(BaseModel):
    field_odata_id: str | None = None
    field_odata_type: str | None = None


class ReferenceCreate(BaseModel):
    field_odata_id: str | None = None


class ReferenceNumeric(Enum):
    field_inf = '-INF'
    inf = 'INF'
    na_n = 'NaN'


class BaseCollectionPaginationCountResponse(BaseModel):
    field_odata_count: int | None = None
    field_odata_next_link: str | None = None


class BaseDeltaFunctionResponse(BaseModel):
    field_odata_next_link: str | None = None
    field_odata_delta_link: str | None = None


class StringCollectionResponse(BaseCollectionPaginationCountResponse):
    value: List[str] | None = None
