# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-02-03T22:13:41+00:00

from __future__ import annotations

from enum import Enum


class ReferenceNumeric(Enum):
    field_inf = '-INF'
    inf = 'INF'
    na_n = 'NaN'
