from __future__ import annotations
from uuid import UUID
from typing import Optional
from pydantic import BaseModel, Field, SerializeAsAny


class DeviceManagement(BaseModel):
	id: Optional[str] = Field(alias="id",default=None,)
	odata_type: Optional[str] = Field(alias="@odata.type",default=None,)
	deviceProtectionOverview: Optional[DeviceProtectionOverview] = Field(alias="deviceProtectionOverview",default=None,)
	intuneAccountId: Optional[UUID] = Field(alias="intuneAccountId",default=None,)
	intuneBrand: Optional[IntuneBrand] = Field(alias="intuneBrand",default=None,)
	settings: Optional[DeviceManagementSettings] = Field(alias="settings",default=None,)
	subscriptionState: Optional[str | DeviceManagementSubscriptionState] = Field(alias="subscriptionState",default=None,)
	userExperienceAnalyticsSettings: Optional[UserExperienceAnalyticsSettings] = Field(alias="userExperienceAnalyticsSettings",default=None,)
	windowsMalwareOverview: Optional[WindowsMalwareOverview] = Field(alias="windowsMalwareOverview",default=None,)
	applePushNotificationCertificate: Optional[ApplePushNotificationCertificate] = Field(alias="applePushNotificationCertificate",default=None,)
	auditEvents: Optional[list[AuditEvent]] = Field(alias="auditEvents",default=None,)
	complianceManagementPartners: Optional[list[ComplianceManagementPartner]] = Field(alias="complianceManagementPartners",default=None,)
	conditionalAccessSettings: Optional[OnPremisesConditionalAccessSettings] = Field(alias="conditionalAccessSettings",default=None,)
	detectedApps: Optional[list[DetectedApp]] = Field(alias="detectedApps",default=None,)
	deviceCategories: Optional[list[DeviceCategory]] = Field(alias="deviceCategories",default=None,)
	deviceCompliancePolicies: SerializeAsAny[Optional[list[DeviceCompliancePolicy]]] = Field(alias="deviceCompliancePolicies",default=None,)
	deviceCompliancePolicyDeviceStateSummary: Optional[DeviceCompliancePolicyDeviceStateSummary] = Field(alias="deviceCompliancePolicyDeviceStateSummary",default=None,)
	deviceCompliancePolicySettingStateSummaries: Optional[list[DeviceCompliancePolicySettingStateSummary]] = Field(alias="deviceCompliancePolicySettingStateSummaries",default=None,)
	deviceConfigurationDeviceStateSummaries: Optional[DeviceConfigurationDeviceStateSummary] = Field(alias="deviceConfigurationDeviceStateSummaries",default=None,)
	deviceConfigurations: SerializeAsAny[Optional[list[DeviceConfiguration]]] = Field(alias="deviceConfigurations",default=None,)
	deviceEnrollmentConfigurations: SerializeAsAny[Optional[list[DeviceEnrollmentConfiguration]]] = Field(alias="deviceEnrollmentConfigurations",default=None,)
	deviceManagementPartners: Optional[list[DeviceManagementPartner]] = Field(alias="deviceManagementPartners",default=None,)
	exchangeConnectors: Optional[list[DeviceManagementExchangeConnector]] = Field(alias="exchangeConnectors",default=None,)
	importedWindowsAutopilotDeviceIdentities: Optional[list[ImportedWindowsAutopilotDeviceIdentity]] = Field(alias="importedWindowsAutopilotDeviceIdentities",default=None,)
	iosUpdateStatuses: Optional[list[IosUpdateDeviceStatus]] = Field(alias="iosUpdateStatuses",default=None,)
	managedDeviceOverview: Optional[ManagedDeviceOverview] = Field(alias="managedDeviceOverview",default=None,)
	managedDevices: Optional[list[ManagedDevice]] = Field(alias="managedDevices",default=None,)
	mobileAppTroubleshootingEvents: Optional[list[MobileAppTroubleshootingEvent]] = Field(alias="mobileAppTroubleshootingEvents",default=None,)
	mobileThreatDefenseConnectors: Optional[list[MobileThreatDefenseConnector]] = Field(alias="mobileThreatDefenseConnectors",default=None,)
	notificationMessageTemplates: Optional[list[NotificationMessageTemplate]] = Field(alias="notificationMessageTemplates",default=None,)
	remoteAssistancePartners: Optional[list[RemoteAssistancePartner]] = Field(alias="remoteAssistancePartners",default=None,)
	reports: Optional[DeviceManagementReports] = Field(alias="reports",default=None,)
	resourceOperations: Optional[list[ResourceOperation]] = Field(alias="resourceOperations",default=None,)
	roleAssignments: Optional[list[DeviceAndAppManagementRoleAssignment]] = Field(alias="roleAssignments",default=None,)
	roleDefinitions: SerializeAsAny[Optional[list[RoleDefinition]]] = Field(alias="roleDefinitions",default=None,)
	softwareUpdateStatusSummary: Optional[SoftwareUpdateStatusSummary] = Field(alias="softwareUpdateStatusSummary",default=None,)
	telecomExpenseManagementPartners: Optional[list[TelecomExpenseManagementPartner]] = Field(alias="telecomExpenseManagementPartners",default=None,)
	termsAndConditions: Optional[list[TermsAndConditions]] = Field(alias="termsAndConditions",default=None,)
	troubleshootingEvents: SerializeAsAny[Optional[list[DeviceManagementTroubleshootingEvent]]] = Field(alias="troubleshootingEvents",default=None,)
	userExperienceAnalyticsAppHealthApplicationPerformance: Optional[list[UserExperienceAnalyticsAppHealthApplicationPerformance]] = Field(alias="userExperienceAnalyticsAppHealthApplicationPerformance",default=None,)
	userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails: Optional[list[UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails]] = Field(alias="userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDetails",default=None,)
	userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDeviceId: Optional[list[UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId]] = Field(alias="userExperienceAnalyticsAppHealthApplicationPerformanceByAppVersionDeviceId",default=None,)
	userExperienceAnalyticsAppHealthApplicationPerformanceByOSVersion: Optional[list[UserExperienceAnalyticsAppHealthAppPerformanceByOSVersion]] = Field(alias="userExperienceAnalyticsAppHealthApplicationPerformanceByOSVersion",default=None,)
	userExperienceAnalyticsAppHealthDeviceModelPerformance: Optional[list[UserExperienceAnalyticsAppHealthDeviceModelPerformance]] = Field(alias="userExperienceAnalyticsAppHealthDeviceModelPerformance",default=None,)
	userExperienceAnalyticsAppHealthDevicePerformance: Optional[list[UserExperienceAnalyticsAppHealthDevicePerformance]] = Field(alias="userExperienceAnalyticsAppHealthDevicePerformance",default=None,)
	userExperienceAnalyticsAppHealthDevicePerformanceDetails: Optional[list[UserExperienceAnalyticsAppHealthDevicePerformanceDetails]] = Field(alias="userExperienceAnalyticsAppHealthDevicePerformanceDetails",default=None,)
	userExperienceAnalyticsAppHealthOSVersionPerformance: Optional[list[UserExperienceAnalyticsAppHealthOSVersionPerformance]] = Field(alias="userExperienceAnalyticsAppHealthOSVersionPerformance",default=None,)
	userExperienceAnalyticsAppHealthOverview: Optional[UserExperienceAnalyticsCategory] = Field(alias="userExperienceAnalyticsAppHealthOverview",default=None,)
	userExperienceAnalyticsBaselines: Optional[list[UserExperienceAnalyticsBaseline]] = Field(alias="userExperienceAnalyticsBaselines",default=None,)
	userExperienceAnalyticsCategories: Optional[list[UserExperienceAnalyticsCategory]] = Field(alias="userExperienceAnalyticsCategories",default=None,)
	userExperienceAnalyticsDevicePerformance: Optional[list[UserExperienceAnalyticsDevicePerformance]] = Field(alias="userExperienceAnalyticsDevicePerformance",default=None,)
	userExperienceAnalyticsDeviceScores: Optional[list[UserExperienceAnalyticsDeviceScores]] = Field(alias="userExperienceAnalyticsDeviceScores",default=None,)
	userExperienceAnalyticsDeviceStartupHistory: Optional[list[UserExperienceAnalyticsDeviceStartupHistory]] = Field(alias="userExperienceAnalyticsDeviceStartupHistory",default=None,)
	userExperienceAnalyticsDeviceStartupProcesses: Optional[list[UserExperienceAnalyticsDeviceStartupProcess]] = Field(alias="userExperienceAnalyticsDeviceStartupProcesses",default=None,)
	userExperienceAnalyticsDeviceStartupProcessPerformance: Optional[list[UserExperienceAnalyticsDeviceStartupProcessPerformance]] = Field(alias="userExperienceAnalyticsDeviceStartupProcessPerformance",default=None,)
	userExperienceAnalyticsMetricHistory: Optional[list[UserExperienceAnalyticsMetricHistory]] = Field(alias="userExperienceAnalyticsMetricHistory",default=None,)
	userExperienceAnalyticsModelScores: Optional[list[UserExperienceAnalyticsModelScores]] = Field(alias="userExperienceAnalyticsModelScores",default=None,)
	userExperienceAnalyticsOverview: Optional[UserExperienceAnalyticsOverview] = Field(alias="userExperienceAnalyticsOverview",default=None,)
	userExperienceAnalyticsScoreHistory: Optional[list[UserExperienceAnalyticsScoreHistory]] = Field(alias="userExperienceAnalyticsScoreHistory",default=None,)
	userExperienceAnalyticsWorkFromAnywhereHardwareReadinessMetric: Optional[UserExperienceAnalyticsWorkFromAnywhereHardwareReadinessMetric] = Field(alias="userExperienceAnalyticsWorkFromAnywhereHardwareReadinessMetric",default=None,)
	userExperienceAnalyticsWorkFromAnywhereMetrics: Optional[list[UserExperienceAnalyticsWorkFromAnywhereMetric]] = Field(alias="userExperienceAnalyticsWorkFromAnywhereMetrics",default=None,)
	userExperienceAnalyticsWorkFromAnywhereModelPerformance: Optional[list[UserExperienceAnalyticsWorkFromAnywhereModelPerformance]] = Field(alias="userExperienceAnalyticsWorkFromAnywhereModelPerformance",default=None,)
	virtualEndpoint: Optional[VirtualEndpoint] = Field(alias="virtualEndpoint",default=None,)
	windowsAutopilotDeviceIdentities: Optional[list[WindowsAutopilotDeviceIdentity]] = Field(alias="windowsAutopilotDeviceIdentities",default=None,)
	windowsInformationProtectionAppLearningSummaries: Optional[list[WindowsInformationProtectionAppLearningSummary]] = Field(alias="windowsInformationProtectionAppLearningSummaries",default=None,)
	windowsInformationProtectionNetworkLearningSummaries: Optional[list[WindowsInformationProtectionNetworkLearningSummary]] = Field(alias="windowsInformationProtectionNetworkLearningSummaries",default=None,)
	windowsMalwareInformation: Optional[list[WindowsMalwareInformation]] = Field(alias="windowsMalwareInformation",default=None,)

from .device_protection_overview import DeviceProtectionOverview
from .intune_brand import IntuneBrand
from .device_management_settings import DeviceManagementSettings
from .device_management_subscription_state import DeviceManagementSubscriptionState
from .user_experience_analytics_settings import UserExperienceAnalyticsSettings
from .windows_malware_overview import WindowsMalwareOverview
from .apple_push_notification_certificate import ApplePushNotificationCertificate
from .audit_event import AuditEvent
from .compliance_management_partner import ComplianceManagementPartner
from .on_premises_conditional_access_settings import OnPremisesConditionalAccessSettings
from .detected_app import DetectedApp
from .device_category import DeviceCategory
from .device_compliance_policy import DeviceCompliancePolicy
from .device_compliance_policy_device_state_summary import DeviceCompliancePolicyDeviceStateSummary
from .device_compliance_policy_setting_state_summary import DeviceCompliancePolicySettingStateSummary
from .device_configuration_device_state_summary import DeviceConfigurationDeviceStateSummary
from .device_configuration import DeviceConfiguration
from .device_enrollment_configuration import DeviceEnrollmentConfiguration
from .device_management_partner import DeviceManagementPartner
from .device_management_exchange_connector import DeviceManagementExchangeConnector
from .imported_windows_autopilot_device_identity import ImportedWindowsAutopilotDeviceIdentity
from .ios_update_device_status import IosUpdateDeviceStatus
from .managed_device_overview import ManagedDeviceOverview
from .managed_device import ManagedDevice
from .mobile_app_troubleshooting_event import MobileAppTroubleshootingEvent
from .mobile_threat_defense_connector import MobileThreatDefenseConnector
from .notification_message_template import NotificationMessageTemplate
from .remote_assistance_partner import RemoteAssistancePartner
from .device_management_reports import DeviceManagementReports
from .resource_operation import ResourceOperation
from .device_and_app_management_role_assignment import DeviceAndAppManagementRoleAssignment
from .role_definition import RoleDefinition
from .software_update_status_summary import SoftwareUpdateStatusSummary
from .telecom_expense_management_partner import TelecomExpenseManagementPartner
from .terms_and_conditions import TermsAndConditions
from .device_management_troubleshooting_event import DeviceManagementTroubleshootingEvent
from .user_experience_analytics_app_health_application_performance import UserExperienceAnalyticsAppHealthApplicationPerformance
from .user_experience_analytics_app_health_app_performance_by_app_version_details import UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDetails
from .user_experience_analytics_app_health_app_performance_by_app_version_device_id import UserExperienceAnalyticsAppHealthAppPerformanceByAppVersionDeviceId
from .user_experience_analytics_app_health_app_performance_by_o_s_version import UserExperienceAnalyticsAppHealthAppPerformanceByOSVersion
from .user_experience_analytics_app_health_device_model_performance import UserExperienceAnalyticsAppHealthDeviceModelPerformance
from .user_experience_analytics_app_health_device_performance import UserExperienceAnalyticsAppHealthDevicePerformance
from .user_experience_analytics_app_health_device_performance_details import UserExperienceAnalyticsAppHealthDevicePerformanceDetails
from .user_experience_analytics_app_health_o_s_version_performance import UserExperienceAnalyticsAppHealthOSVersionPerformance
from .user_experience_analytics_category import UserExperienceAnalyticsCategory
from .user_experience_analytics_baseline import UserExperienceAnalyticsBaseline
from .user_experience_analytics_category import UserExperienceAnalyticsCategory
from .user_experience_analytics_device_performance import UserExperienceAnalyticsDevicePerformance
from .user_experience_analytics_device_scores import UserExperienceAnalyticsDeviceScores
from .user_experience_analytics_device_startup_history import UserExperienceAnalyticsDeviceStartupHistory
from .user_experience_analytics_device_startup_process import UserExperienceAnalyticsDeviceStartupProcess
from .user_experience_analytics_device_startup_process_performance import UserExperienceAnalyticsDeviceStartupProcessPerformance
from .user_experience_analytics_metric_history import UserExperienceAnalyticsMetricHistory
from .user_experience_analytics_model_scores import UserExperienceAnalyticsModelScores
from .user_experience_analytics_overview import UserExperienceAnalyticsOverview
from .user_experience_analytics_score_history import UserExperienceAnalyticsScoreHistory
from .user_experience_analytics_work_from_anywhere_hardware_readiness_metric import UserExperienceAnalyticsWorkFromAnywhereHardwareReadinessMetric
from .user_experience_analytics_work_from_anywhere_metric import UserExperienceAnalyticsWorkFromAnywhereMetric
from .user_experience_analytics_work_from_anywhere_model_performance import UserExperienceAnalyticsWorkFromAnywhereModelPerformance
from .virtual_endpoint import VirtualEndpoint
from .windows_autopilot_device_identity import WindowsAutopilotDeviceIdentity
from .windows_information_protection_app_learning_summary import WindowsInformationProtectionAppLearningSummary
from .windows_information_protection_network_learning_summary import WindowsInformationProtectionNetworkLearningSummary
from .windows_malware_information import WindowsMalwareInformation

