from __future__ import annotations
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field, SerializeAsAny


class Group(BaseModel):
	id: Optional[str] = Field(default=None,alias="id",)
	odata_type: Optional[str] = Field(default=None,alias="@odata.type",)
	deletedDateTime: Optional[datetime] = Field(default=None,alias="deletedDateTime",)
	allowExternalSenders: Optional[bool] = Field(default=None,alias="allowExternalSenders",)
	assignedLabels: Optional[list[AssignedLabel]] = Field(default=None,alias="assignedLabels",)
	assignedLicenses: Optional[list[AssignedLicense]] = Field(default=None,alias="assignedLicenses",)
	autoSubscribeNewMembers: Optional[bool] = Field(default=None,alias="autoSubscribeNewMembers",)
	classification: Optional[str] = Field(default=None,alias="classification",)
	createdDateTime: Optional[datetime] = Field(default=None,alias="createdDateTime",)
	description: Optional[str] = Field(default=None,alias="description",)
	displayName: Optional[str] = Field(default=None,alias="displayName",)
	expirationDateTime: Optional[datetime] = Field(default=None,alias="expirationDateTime",)
	groupTypes: Optional[list[str]] = Field(default=None,alias="groupTypes",)
	hasMembersWithLicenseErrors: Optional[bool] = Field(default=None,alias="hasMembersWithLicenseErrors",)
	hideFromAddressLists: Optional[bool] = Field(default=None,alias="hideFromAddressLists",)
	hideFromOutlookClients: Optional[bool] = Field(default=None,alias="hideFromOutlookClients",)
	isArchived: Optional[bool] = Field(default=None,alias="isArchived",)
	isAssignableToRole: Optional[bool] = Field(default=None,alias="isAssignableToRole",)
	isManagementRestricted: Optional[bool] = Field(default=None,alias="isManagementRestricted",)
	isSubscribedByMail: Optional[bool] = Field(default=None,alias="isSubscribedByMail",)
	licenseProcessingState: Optional[LicenseProcessingState] = Field(default=None,alias="licenseProcessingState",)
	mail: Optional[str] = Field(default=None,alias="mail",)
	mailEnabled: Optional[bool] = Field(default=None,alias="mailEnabled",)
	mailNickname: Optional[str] = Field(default=None,alias="mailNickname",)
	membershipRule: Optional[str] = Field(default=None,alias="membershipRule",)
	membershipRuleProcessingState: Optional[str] = Field(default=None,alias="membershipRuleProcessingState",)
	onPremisesDomainName: Optional[str] = Field(default=None,alias="onPremisesDomainName",)
	onPremisesLastSyncDateTime: Optional[datetime] = Field(default=None,alias="onPremisesLastSyncDateTime",)
	onPremisesNetBiosName: Optional[str] = Field(default=None,alias="onPremisesNetBiosName",)
	onPremisesProvisioningErrors: Optional[list[OnPremisesProvisioningError]] = Field(default=None,alias="onPremisesProvisioningErrors",)
	onPremisesSamAccountName: Optional[str] = Field(default=None,alias="onPremisesSamAccountName",)
	onPremisesSecurityIdentifier: Optional[str] = Field(default=None,alias="onPremisesSecurityIdentifier",)
	onPremisesSyncEnabled: Optional[bool] = Field(default=None,alias="onPremisesSyncEnabled",)
	preferredDataLocation: Optional[str] = Field(default=None,alias="preferredDataLocation",)
	preferredLanguage: Optional[str] = Field(default=None,alias="preferredLanguage",)
	proxyAddresses: Optional[list[str]] = Field(default=None,alias="proxyAddresses",)
	renewedDateTime: Optional[datetime] = Field(default=None,alias="renewedDateTime",)
	securityEnabled: Optional[bool] = Field(default=None,alias="securityEnabled",)
	securityIdentifier: Optional[str] = Field(default=None,alias="securityIdentifier",)
	serviceProvisioningErrors: SerializeAsAny[Optional[list[ServiceProvisioningError]]] = Field(default=None,alias="serviceProvisioningErrors",)
	theme: Optional[str] = Field(default=None,alias="theme",)
	uniqueName: Optional[str] = Field(default=None,alias="uniqueName",)
	unseenCount: Optional[int] = Field(default=None,alias="unseenCount",)
	visibility: Optional[str] = Field(default=None,alias="visibility",)
	acceptedSenders: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="acceptedSenders",)
	appRoleAssignments: Optional[list[AppRoleAssignment]] = Field(default=None,alias="appRoleAssignments",)
	calendar: Optional[Calendar] = Field(default=None,alias="calendar",)
	calendarView: Optional[list[Event]] = Field(default=None,alias="calendarView",)
	conversations: Optional[list[Conversation]] = Field(default=None,alias="conversations",)
	createdOnBehalfOf: SerializeAsAny[Optional[DirectoryObject]] = Field(default=None,alias="createdOnBehalfOf",)
	drive: Optional[Drive] = Field(default=None,alias="drive",)
	drives: Optional[list[Drive]] = Field(default=None,alias="drives",)
	events: Optional[list[Event]] = Field(default=None,alias="events",)
	extensions: SerializeAsAny[Optional[list[Extension]]] = Field(default=None,alias="extensions",)
	groupLifecyclePolicies: Optional[list[GroupLifecyclePolicy]] = Field(default=None,alias="groupLifecyclePolicies",)
	memberOf: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="memberOf",)
	members: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="members",)
	membersWithLicenseErrors: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="membersWithLicenseErrors",)
	onenote: Optional[Onenote] = Field(default=None,alias="onenote",)
	owners: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="owners",)
	permissionGrants: Optional[list[ResourceSpecificPermissionGrant]] = Field(default=None,alias="permissionGrants",)
	photo: Optional[ProfilePhoto] = Field(default=None,alias="photo",)
	photos: Optional[list[ProfilePhoto]] = Field(default=None,alias="photos",)
	planner: Optional[PlannerGroup] = Field(default=None,alias="planner",)
	rejectedSenders: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="rejectedSenders",)
	settings: Optional[list[GroupSetting]] = Field(default=None,alias="settings",)
	sites: Optional[list[Site]] = Field(default=None,alias="sites",)
	team: Optional[Team] = Field(default=None,alias="team",)
	threads: Optional[list[ConversationThread]] = Field(default=None,alias="threads",)
	transitiveMemberOf: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="transitiveMemberOf",)
	transitiveMembers: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="transitiveMembers",)

from .assigned_label import AssignedLabel
from .assigned_license import AssignedLicense
from .license_processing_state import LicenseProcessingState
from .on_premises_provisioning_error import OnPremisesProvisioningError
from .service_provisioning_error import ServiceProvisioningError
from .directory_object import DirectoryObject
from .app_role_assignment import AppRoleAssignment
from .calendar import Calendar
from .event import Event
from .conversation import Conversation
from .directory_object import DirectoryObject
from .drive import Drive
from .drive import Drive
from .event import Event
from .extension import Extension
from .group_lifecycle_policy import GroupLifecyclePolicy
from .directory_object import DirectoryObject
from .directory_object import DirectoryObject
from .directory_object import DirectoryObject
from .onenote import Onenote
from .directory_object import DirectoryObject
from .resource_specific_permission_grant import ResourceSpecificPermissionGrant
from .profile_photo import ProfilePhoto
from .profile_photo import ProfilePhoto
from .planner_group import PlannerGroup
from .directory_object import DirectoryObject
from .group_setting import GroupSetting
from .site import Site
from .team import Team
from .conversation_thread import ConversationThread
from .directory_object import DirectoryObject
from .directory_object import DirectoryObject

