from __future__ import annotations
from typing import Optional
from datetime import datetime
from pydantic import BaseModel, Field, SerializeAsAny


class User(BaseModel):
	id: Optional[str] = Field(default=None,alias="id",)
	odata_type: Optional[str] = Field(default=None,alias="@odata.type",)
	deletedDateTime: Optional[datetime] = Field(default=None,alias="deletedDateTime",)
	aboutMe: Optional[str] = Field(default=None,alias="aboutMe",)
	accountEnabled: Optional[bool] = Field(default=None,alias="accountEnabled",)
	ageGroup: Optional[str] = Field(default=None,alias="ageGroup",)
	assignedLicenses: Optional[list[AssignedLicense]] = Field(default=None,alias="assignedLicenses",)
	assignedPlans: Optional[list[AssignedPlan]] = Field(default=None,alias="assignedPlans",)
	authorizationInfo: Optional[AuthorizationInfo] = Field(default=None,alias="authorizationInfo",)
	birthday: Optional[datetime] = Field(default=None,alias="birthday",)
	businessPhones: Optional[list[str]] = Field(default=None,alias="businessPhones",)
	city: Optional[str] = Field(default=None,alias="city",)
	companyName: Optional[str] = Field(default=None,alias="companyName",)
	consentProvidedForMinor: Optional[str] = Field(default=None,alias="consentProvidedForMinor",)
	country: Optional[str] = Field(default=None,alias="country",)
	createdDateTime: Optional[datetime] = Field(default=None,alias="createdDateTime",)
	creationType: Optional[str] = Field(default=None,alias="creationType",)
	customSecurityAttributes: Optional[CustomSecurityAttributeValue] = Field(default=None,alias="customSecurityAttributes",)
	department: Optional[str] = Field(default=None,alias="department",)
	deviceEnrollmentLimit: Optional[int] = Field(default=None,alias="deviceEnrollmentLimit",)
	displayName: Optional[str] = Field(default=None,alias="displayName",)
	employeeHireDate: Optional[datetime] = Field(default=None,alias="employeeHireDate",)
	employeeId: Optional[str] = Field(default=None,alias="employeeId",)
	employeeLeaveDateTime: Optional[datetime] = Field(default=None,alias="employeeLeaveDateTime",)
	employeeOrgData: Optional[EmployeeOrgData] = Field(default=None,alias="employeeOrgData",)
	employeeType: Optional[str] = Field(default=None,alias="employeeType",)
	externalUserState: Optional[str] = Field(default=None,alias="externalUserState",)
	externalUserStateChangeDateTime: Optional[datetime] = Field(default=None,alias="externalUserStateChangeDateTime",)
	faxNumber: Optional[str] = Field(default=None,alias="faxNumber",)
	givenName: Optional[str] = Field(default=None,alias="givenName",)
	hireDate: Optional[datetime] = Field(default=None,alias="hireDate",)
	identities: Optional[list[ObjectIdentity]] = Field(default=None,alias="identities",)
	imAddresses: Optional[list[str]] = Field(default=None,alias="imAddresses",)
	interests: Optional[list[str]] = Field(default=None,alias="interests",)
	isManagementRestricted: Optional[bool] = Field(default=None,alias="isManagementRestricted",)
	isResourceAccount: Optional[bool] = Field(default=None,alias="isResourceAccount",)
	jobTitle: Optional[str] = Field(default=None,alias="jobTitle",)
	lastPasswordChangeDateTime: Optional[datetime] = Field(default=None,alias="lastPasswordChangeDateTime",)
	legalAgeGroupClassification: Optional[str] = Field(default=None,alias="legalAgeGroupClassification",)
	licenseAssignmentStates: Optional[list[LicenseAssignmentState]] = Field(default=None,alias="licenseAssignmentStates",)
	mail: Optional[str] = Field(default=None,alias="mail",)
	mailboxSettings: Optional[MailboxSettings] = Field(default=None,alias="mailboxSettings",)
	mailNickname: Optional[str] = Field(default=None,alias="mailNickname",)
	mobilePhone: Optional[str] = Field(default=None,alias="mobilePhone",)
	mySite: Optional[str] = Field(default=None,alias="mySite",)
	officeLocation: Optional[str] = Field(default=None,alias="officeLocation",)
	onPremisesDistinguishedName: Optional[str] = Field(default=None,alias="onPremisesDistinguishedName",)
	onPremisesDomainName: Optional[str] = Field(default=None,alias="onPremisesDomainName",)
	onPremisesExtensionAttributes: Optional[OnPremisesExtensionAttributes] = Field(default=None,alias="onPremisesExtensionAttributes",)
	onPremisesImmutableId: Optional[str] = Field(default=None,alias="onPremisesImmutableId",)
	onPremisesLastSyncDateTime: Optional[datetime] = Field(default=None,alias="onPremisesLastSyncDateTime",)
	onPremisesProvisioningErrors: Optional[list[OnPremisesProvisioningError]] = Field(default=None,alias="onPremisesProvisioningErrors",)
	onPremisesSamAccountName: Optional[str] = Field(default=None,alias="onPremisesSamAccountName",)
	onPremisesSecurityIdentifier: Optional[str] = Field(default=None,alias="onPremisesSecurityIdentifier",)
	onPremisesSyncEnabled: Optional[bool] = Field(default=None,alias="onPremisesSyncEnabled",)
	onPremisesUserPrincipalName: Optional[str] = Field(default=None,alias="onPremisesUserPrincipalName",)
	otherMails: Optional[list[str]] = Field(default=None,alias="otherMails",)
	passwordPolicies: Optional[str] = Field(default=None,alias="passwordPolicies",)
	passwordProfile: Optional[PasswordProfile] = Field(default=None,alias="passwordProfile",)
	pastProjects: Optional[list[str]] = Field(default=None,alias="pastProjects",)
	postalCode: Optional[str] = Field(default=None,alias="postalCode",)
	preferredDataLocation: Optional[str] = Field(default=None,alias="preferredDataLocation",)
	preferredLanguage: Optional[str] = Field(default=None,alias="preferredLanguage",)
	preferredName: Optional[str] = Field(default=None,alias="preferredName",)
	print: Optional[UserPrint] = Field(default=None,alias="print",)
	provisionedPlans: Optional[list[ProvisionedPlan]] = Field(default=None,alias="provisionedPlans",)
	proxyAddresses: Optional[list[str]] = Field(default=None,alias="proxyAddresses",)
	responsibilities: Optional[list[str]] = Field(default=None,alias="responsibilities",)
	schools: Optional[list[str]] = Field(default=None,alias="schools",)
	securityIdentifier: Optional[str] = Field(default=None,alias="securityIdentifier",)
	serviceProvisioningErrors: SerializeAsAny[Optional[list[ServiceProvisioningError]]] = Field(default=None,alias="serviceProvisioningErrors",)
	showInAddressList: Optional[bool] = Field(default=None,alias="showInAddressList",)
	signInActivity: Optional[SignInActivity] = Field(default=None,alias="signInActivity",)
	signInSessionsValidFromDateTime: Optional[datetime] = Field(default=None,alias="signInSessionsValidFromDateTime",)
	skills: Optional[list[str]] = Field(default=None,alias="skills",)
	state: Optional[str] = Field(default=None,alias="state",)
	streetAddress: Optional[str] = Field(default=None,alias="streetAddress",)
	surname: Optional[str] = Field(default=None,alias="surname",)
	usageLocation: Optional[str] = Field(default=None,alias="usageLocation",)
	userPrincipalName: Optional[str] = Field(default=None,alias="userPrincipalName",)
	userType: Optional[str] = Field(default=None,alias="userType",)
	activities: Optional[list[UserActivity]] = Field(default=None,alias="activities",)
	agreementAcceptances: Optional[list[AgreementAcceptance]] = Field(default=None,alias="agreementAcceptances",)
	appRoleAssignments: Optional[list[AppRoleAssignment]] = Field(default=None,alias="appRoleAssignments",)
	authentication: Optional[Authentication] = Field(default=None,alias="authentication",)
	calendar: Optional[Calendar] = Field(default=None,alias="calendar",)
	calendarGroups: Optional[list[CalendarGroup]] = Field(default=None,alias="calendarGroups",)
	calendars: Optional[list[Calendar]] = Field(default=None,alias="calendars",)
	calendarView: Optional[list[Event]] = Field(default=None,alias="calendarView",)
	chats: Optional[list[Chat]] = Field(default=None,alias="chats",)
	cloudClipboard: Optional[CloudClipboardRoot] = Field(default=None,alias="cloudClipboard",)
	contactFolders: Optional[list[ContactFolder]] = Field(default=None,alias="contactFolders",)
	contacts: Optional[list[Contact]] = Field(default=None,alias="contacts",)
	createdObjects: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="createdObjects",)
	deviceManagementTroubleshootingEvents: SerializeAsAny[Optional[list[DeviceManagementTroubleshootingEvent]]] = Field(default=None,alias="deviceManagementTroubleshootingEvents",)
	directReports: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="directReports",)
	drive: Optional[Drive] = Field(default=None,alias="drive",)
	drives: Optional[list[Drive]] = Field(default=None,alias="drives",)
	employeeExperience: Optional[EmployeeExperienceUser] = Field(default=None,alias="employeeExperience",)
	events: Optional[list[Event]] = Field(default=None,alias="events",)
	extensions: SerializeAsAny[Optional[list[Extension]]] = Field(default=None,alias="extensions",)
	followedSites: Optional[list[Site]] = Field(default=None,alias="followedSites",)
	inferenceClassification: Optional[InferenceClassification] = Field(default=None,alias="inferenceClassification",)
	insights: Optional[ItemInsights] = Field(default=None,alias="insights",)
	joinedTeams: Optional[list[Team]] = Field(default=None,alias="joinedTeams",)
	licenseDetails: Optional[list[LicenseDetails]] = Field(default=None,alias="licenseDetails",)
	mailFolders: SerializeAsAny[Optional[list[MailFolder]]] = Field(default=None,alias="mailFolders",)
	managedAppRegistrations: SerializeAsAny[Optional[list[ManagedAppRegistration]]] = Field(default=None,alias="managedAppRegistrations",)
	managedDevices: Optional[list[ManagedDevice]] = Field(default=None,alias="managedDevices",)
	manager: SerializeAsAny[Optional[DirectoryObject]] = Field(default=None,alias="manager",)
	memberOf: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="memberOf",)
	messages: SerializeAsAny[Optional[list[Message]]] = Field(default=None,alias="messages",)
	oauth2PermissionGrants: Optional[list[OAuth2PermissionGrant]] = Field(default=None,alias="oauth2PermissionGrants",)
	onenote: Optional[Onenote] = Field(default=None,alias="onenote",)
	onlineMeetings: Optional[list[OnlineMeeting]] = Field(default=None,alias="onlineMeetings",)
	outlook: Optional[OutlookUser] = Field(default=None,alias="outlook",)
	ownedDevices: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="ownedDevices",)
	ownedObjects: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="ownedObjects",)
	people: Optional[list[Person]] = Field(default=None,alias="people",)
	permissionGrants: Optional[list[ResourceSpecificPermissionGrant]] = Field(default=None,alias="permissionGrants",)
	photo: Optional[ProfilePhoto] = Field(default=None,alias="photo",)
	photos: Optional[list[ProfilePhoto]] = Field(default=None,alias="photos",)
	planner: Optional[PlannerUser] = Field(default=None,alias="planner",)
	presence: Optional[Presence] = Field(default=None,alias="presence",)
	registeredDevices: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="registeredDevices",)
	scopedRoleMemberOf: Optional[list[ScopedRoleMembership]] = Field(default=None,alias="scopedRoleMemberOf",)
	settings: Optional[UserSettings] = Field(default=None,alias="settings",)
	solutions: Optional[UserSolutionRoot] = Field(default=None,alias="solutions",)
	sponsors: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="sponsors",)
	teamwork: Optional[UserTeamwork] = Field(default=None,alias="teamwork",)
	todo: Optional[Todo] = Field(default=None,alias="todo",)
	transitiveMemberOf: SerializeAsAny[Optional[list[DirectoryObject]]] = Field(default=None,alias="transitiveMemberOf",)

from .assigned_license import AssignedLicense
from .assigned_plan import AssignedPlan
from .authorization_info import AuthorizationInfo
from .custom_security_attribute_value import CustomSecurityAttributeValue
from .employee_org_data import EmployeeOrgData
from .object_identity import ObjectIdentity
from .license_assignment_state import LicenseAssignmentState
from .mailbox_settings import MailboxSettings
from .on_premises_extension_attributes import OnPremisesExtensionAttributes
from .on_premises_provisioning_error import OnPremisesProvisioningError
from .password_profile import PasswordProfile
from .user_print import UserPrint
from .provisioned_plan import ProvisionedPlan
from .service_provisioning_error import ServiceProvisioningError
from .sign_in_activity import SignInActivity
from .user_activity import UserActivity
from .agreement_acceptance import AgreementAcceptance
from .app_role_assignment import AppRoleAssignment
from .authentication import Authentication
from .calendar import Calendar
from .calendar_group import CalendarGroup
from .calendar import Calendar
from .event import Event
from .chat import Chat
from .cloud_clipboard_root import CloudClipboardRoot
from .contact_folder import ContactFolder
from .contact import Contact
from .directory_object import DirectoryObject
from .device_management_troubleshooting_event import DeviceManagementTroubleshootingEvent
from .directory_object import DirectoryObject
from .drive import Drive
from .drive import Drive
from .employee_experience_user import EmployeeExperienceUser
from .event import Event
from .extension import Extension
from .site import Site
from .inference_classification import InferenceClassification
from .item_insights import ItemInsights
from .team import Team
from .license_details import LicenseDetails
from .mail_folder import MailFolder
from .managed_app_registration import ManagedAppRegistration
from .managed_device import ManagedDevice
from .directory_object import DirectoryObject
from .directory_object import DirectoryObject
from .message import Message
from .o_auth2_permission_grant import OAuth2PermissionGrant
from .onenote import Onenote
from .online_meeting import OnlineMeeting
from .outlook_user import OutlookUser
from .directory_object import DirectoryObject
from .directory_object import DirectoryObject
from .person import Person
from .resource_specific_permission_grant import ResourceSpecificPermissionGrant
from .profile_photo import ProfilePhoto
from .profile_photo import ProfilePhoto
from .planner_user import PlannerUser
from .presence import Presence
from .directory_object import DirectoryObject
from .scoped_role_membership import ScopedRoleMembership
from .user_settings import UserSettings
from .user_solution_root import UserSolutionRoot
from .directory_object import DirectoryObject
from .user_teamwork import UserTeamwork
from .todo import Todo
from .directory_object import DirectoryObject

