from __future__ import annotations
from typing import Optional
from typing import Union
from typing import Literal
from datetime import datetime
from pydantic import BaseModel, Field


class ChatMessageInfo(BaseModel):
	id: Optional[str] = Field(alias="id", default=None,)
	odata_type: Literal["#microsoft.graph.chatMessageInfo"] = Field(alias="@odata.type",)
	body: Optional[ItemBody] = Field(alias="body", default=None,)
	createdDateTime: Optional[datetime] = Field(alias="createdDateTime", default=None,)
	eventDetail: Optional[Union[CallEndedEventMessageDetail, CallRecordingEventMessageDetail, CallStartedEventMessageDetail, CallTranscriptEventMessageDetail, ChannelAddedEventMessageDetail, ChannelDeletedEventMessageDetail, ChannelDescriptionUpdatedEventMessageDetail, ChannelRenamedEventMessageDetail, ChannelSetAsFavoriteByDefaultEventMessageDetail, ChannelUnsetAsFavoriteByDefaultEventMessageDetail, ChatRenamedEventMessageDetail, ConversationMemberRoleUpdatedEventMessageDetail, MeetingPolicyUpdatedEventMessageDetail, MembersAddedEventMessageDetail, MembersDeletedEventMessageDetail, MembersJoinedEventMessageDetail, MembersLeftEventMessageDetail, MessagePinnedEventMessageDetail, MessageUnpinnedEventMessageDetail, TabUpdatedEventMessageDetail, TeamArchivedEventMessageDetail, TeamCreatedEventMessageDetail, TeamDescriptionUpdatedEventMessageDetail, TeamJoiningDisabledEventMessageDetail, TeamJoiningEnabledEventMessageDetail, TeamRenamedEventMessageDetail, TeamsAppInstalledEventMessageDetail, TeamsAppRemovedEventMessageDetail, TeamsAppUpgradedEventMessageDetail, TeamUnarchivedEventMessageDetail]] = Field(alias="eventDetail", default=None,discriminator="odata_type", )
	from_: Optional[ChatMessageFromIdentitySet] = Field(alias="from", default=None,)
	isDeleted: Optional[bool] = Field(alias="isDeleted", default=None,)
	messageType: Optional[ChatMessageType | str] = Field(alias="messageType", default=None,)

from .item_body import ItemBody
from .call_ended_event_message_detail import CallEndedEventMessageDetail
from .call_recording_event_message_detail import CallRecordingEventMessageDetail
from .call_started_event_message_detail import CallStartedEventMessageDetail
from .call_transcript_event_message_detail import CallTranscriptEventMessageDetail
from .channel_added_event_message_detail import ChannelAddedEventMessageDetail
from .channel_deleted_event_message_detail import ChannelDeletedEventMessageDetail
from .channel_description_updated_event_message_detail import ChannelDescriptionUpdatedEventMessageDetail
from .channel_renamed_event_message_detail import ChannelRenamedEventMessageDetail
from .channel_set_as_favorite_by_default_event_message_detail import ChannelSetAsFavoriteByDefaultEventMessageDetail
from .channel_unset_as_favorite_by_default_event_message_detail import ChannelUnsetAsFavoriteByDefaultEventMessageDetail
from .chat_renamed_event_message_detail import ChatRenamedEventMessageDetail
from .conversation_member_role_updated_event_message_detail import ConversationMemberRoleUpdatedEventMessageDetail
from .meeting_policy_updated_event_message_detail import MeetingPolicyUpdatedEventMessageDetail
from .members_added_event_message_detail import MembersAddedEventMessageDetail
from .members_deleted_event_message_detail import MembersDeletedEventMessageDetail
from .members_joined_event_message_detail import MembersJoinedEventMessageDetail
from .members_left_event_message_detail import MembersLeftEventMessageDetail
from .message_pinned_event_message_detail import MessagePinnedEventMessageDetail
from .message_unpinned_event_message_detail import MessageUnpinnedEventMessageDetail
from .tab_updated_event_message_detail import TabUpdatedEventMessageDetail
from .team_archived_event_message_detail import TeamArchivedEventMessageDetail
from .team_created_event_message_detail import TeamCreatedEventMessageDetail
from .team_description_updated_event_message_detail import TeamDescriptionUpdatedEventMessageDetail
from .team_joining_disabled_event_message_detail import TeamJoiningDisabledEventMessageDetail
from .team_joining_enabled_event_message_detail import TeamJoiningEnabledEventMessageDetail
from .team_renamed_event_message_detail import TeamRenamedEventMessageDetail
from .teams_app_installed_event_message_detail import TeamsAppInstalledEventMessageDetail
from .teams_app_removed_event_message_detail import TeamsAppRemovedEventMessageDetail
from .teams_app_upgraded_event_message_detail import TeamsAppUpgradedEventMessageDetail
from .team_unarchived_event_message_detail import TeamUnarchivedEventMessageDetail
from .chat_message_from_identity_set import ChatMessageFromIdentitySet
from .chat_message_type import ChatMessageType
